// Year 4 Whole Numbers - follow-on Easy banks, source-grounded in the
// Year 4 textbooks:
//   1.1.2 Explore Numbers (place value and digit value)
//   1.1.2 Compare and Arrange Numbers
//   1.2.1-1.2.2 Even Numbers and Odd Numbers
//   1.5.1-1.5.2 Number Patterns
//
// Exactly five questions per subtopic bank, each with per-option feedback,
// question type, review focus, difficulty metadata, and bilingual locators.
const {
  CONTENT_VERSION,
  AUTHOR_ID,
  REVIEWER_ID,
  APPROVED_AT,
} = require("./content_source_manifest");

const topicId = "whole_numbers_y4";
const createdAt = "2026-08-12T00:00:00Z";
const enMaterialId = "en_y4";
const bmMaterialId = "bm_y4";
const enBook = "Mathematics Year 4 SK (DLP)";
const bmBook = "Buku Teks Matematik Tahun 4";

const definitions = [
  {
    subtopicId: "place_digit_value",
    skillId: "y4_whole_numbers_place_value",
    standardCode: "1.1.2 Explore Numbers / Teroka Nombor",
    enPages: "p. 5",
    bmPages: "hlm. 5",
    reviewFocus:
      "Find the digit, name its place from the right, then state the digit value.",
    reviewFocusBm:
      "Cari digit, namakan tempatnya dari kanan, kemudian nyatakan nilai digit.",
    questions: [
      [
        "01",
        "In 62 307, what is the value of digit 6?",
        "Dalam 62 307, apakah nilai digit 6?",
        ["6", "60", "6 000", "60 000"],
        ["6", "60", "6 000", "60 000"],
        3,
        "Choose the value of a digit",
        "Pilih nilai bagi sesuatu digit",
        {
          "0": {
            misconceptionCode: "digit_value_as_digit",
            hint: "Digit 6 is in the ten-thousands place, so its value is much bigger than 6.",
            hintBm: "Digit 6 berada di tempat puluh ribu, jadi nilainya jauh lebih besar daripada 6.",
            example: "In 81 000, the 8 is worth 80 000.",
            exampleBm: "Dalam 81 000, digit 8 bernilai 80 000.",
            reviewFocus: "Count the place of the digit from the right.",
            reviewFocusBm: "Kira tempat digit dari kanan.",
          },
          "1": {
            misconceptionCode: "place_miscount",
            hint: "The 6 is the first digit of a five-digit number, which is the ten-thousands place.",
            hintBm: "Digit 6 ialah digit pertama bagi nombor lima digit, iaitu tempat puluh ribu.",
            example: "In 52 000, the 5 is worth 50 000.",
            exampleBm: "Dalam 52 000, digit 5 bernilai 50 000.",
            reviewFocus: "Check the digit is five places from the right.",
            reviewFocusBm: "Semak digit berada lima tempat dari kanan.",
          },
          "2": {
            misconceptionCode: "thousands_value_confused",
            hint: "The thousands digit in 62 307 is 2, not 6. The 6 is one place further left.",
            hintBm: "Digit ribu dalam 62 307 ialah 2, bukan 6. Digit 6 berada satu tempat lebih kiri.",
            example: "In 74 000, the 7 is worth 70 000.",
            exampleBm: "Dalam 74 000, digit 7 bernilai 70 000.",
            reviewFocus: "Compare the ten-thousands place with the thousands place.",
            reviewFocusBm: "Bandingkan tempat puluh ribu dengan tempat ribu.",
          },
        },
      ],
      [
        "02",
        "Which digit is in the hundreds place in 62 307?",
        "Digit manakah berada di tempat ratus dalam 62 307?",
        ["7", "3", "2", "6"],
        ["7", "3", "2", "6"],
        1,
        "Find a digit by its place",
        "Cari digit mengikut tempatnya",
        {
          "0": {
            misconceptionCode: "place_miscount",
            hint: "The hundreds place is the third digit from the right, not the first.",
            hintBm: "Tempat ratus ialah digit ketiga dari kanan, bukan yang pertama.",
            example: "In 41 208, the hundreds digit is 2.",
            exampleBm: "Dalam 41 208, digit ratus ialah 2.",
            reviewFocus: "Count three places from the right.",
            reviewFocusBm: "Kira tiga tempat dari kanan.",
          },
          "2": {
            misconceptionCode: "thousands_place_confused",
            hint: "The 2 is one place further left than hundreds; it is in the thousands place.",
            hintBm: "Digit 2 berada satu tempat lebih kiri daripada ratus; ia berada di tempat ribu.",
            example: "In 53 009, the thousands digit is 3.",
            exampleBm: "Dalam 53 009, digit ribu ialah 3.",
            reviewFocus: "Distinguish thousands from hundreds.",
            reviewFocusBm: "Bezakan ribu dengan ratus.",
          },
          "3": {
            misconceptionCode: "digit_value_confused",
            hint: "The 6 is the first digit of the number, so it is in the ten-thousands place.",
            hintBm: "Digit 6 ialah digit pertama nombor, jadi ia berada di tempat puluh ribu.",
            example: "In 90 123, the ten-thousands digit is 9.",
            exampleBm: "Dalam 90 123, digit puluh ribu ialah 9.",
            reviewFocus: "Check the first digit is not the hundreds digit.",
            reviewFocusBm: "Semak digit pertama bukan digit ratus.",
          },
        },
      ],
      [
        "03",
        "What is the place value of 2 in 62 307?",
        "Apakah nilai tempat bagi 2 dalam 62 307?",
        ["ones", "tens", "hundreds", "thousands"],
        ["sa", "puluh", "ratus", "ribu"],
        3,
        "Name a digit's place",
        "Namakan tempat bagi sesuatu digit",
        {
          "0": {
            misconceptionCode: "place_miscount",
            hint: "The 2 is not the last digit. Count its position from the right of the number.",
            hintBm: "Digit 2 bukan digit terakhir. Kira kedudukannya dari kanan nombor.",
            example: "In 87 100, the digit 7 is in the thousands place.",
            exampleBm: "Dalam 87 100, digit 7 berada di tempat ribu.",
            reviewFocus: "Count places from the ones place.",
            reviewFocusBm: "Kira tempat bermula daripada tempat sa.",
          },
          "1": {
            misconceptionCode: "place_miscount",
            hint: "The 2 is the fourth digit from the right, so it is not the tens place.",
            hintBm: "Digit 2 ialah digit keempat dari kanan, jadi ia bukan tempat puluh.",
            example: "In 51 430, the tens digit is 3.",
            exampleBm: "Dalam 51 430, digit puluh ialah 3.",
            reviewFocus: "Compare with the digit just before the ones.",
            reviewFocusBm: "Bandingkan dengan digit sebelum sa.",
          },
          "2": {
            misconceptionCode: "hundreds_place_confused",
            hint: "The hundreds digit in 62 307 is 3. The 2 is one place further left.",
            hintBm: "Digit ratus dalam 62 307 ialah 3. Digit 2 berada satu tempat lebih kiri.",
            example: "In 46 812, the hundreds digit is 8.",
            exampleBm: "Dalam 46 812, digit ratus ialah 8.",
            reviewFocus: "Check the position of 2 compared with 3.",
            reviewFocusBm: "Semak kedudukan digit 2 berbanding digit 3.",
          },
        },
      ],
      [
        "04",
        "Which expanded form is 62 307?",
        "Bentuk cerakin manakah ialah 62 307?",
        [
          "60 000 + 2 000 + 300 + 7",
          "60 000 + 200 + 30 + 7",
          "6 000 + 2 000 + 300 + 7",
          "62 000 + 307",
        ],
        [
          "60 000 + 2 000 + 300 + 7",
          "60 000 + 200 + 30 + 7",
          "6 000 + 2 000 + 300 + 7",
          "62 000 + 307",
        ],
        0,
        "Choose the expanded form",
        "Pilih bentuk cerakin",
        {
          "1": {
            misconceptionCode: "digit_value_as_digit",
            hint: "The 3 is in the hundreds place, so it is 300, not 30.",
            hintBm: "Digit 3 berada di tempat ratus, jadi ia ialah 300, bukan 30.",
            example: "In 41 205, the 2 is worth 200.",
            exampleBm: "Dalam 41 205, digit 2 bernilai 200.",
            reviewFocus: "Give every digit its place value.",
            reviewFocusBm: "Beri setiap digit nilai tempatnya.",
          },
          "2": {
            misconceptionCode: "thousands_value_confused",
            hint: "The 6 is in the ten-thousands place, so it is 60 000, not 6 000.",
            hintBm: "Digit 6 berada di tempat puluh ribu, jadi ia ialah 60 000, bukan 6 000.",
            example: "In 52 000, the 5 is worth 50 000.",
            exampleBm: "Dalam 52 000, digit 5 bernilai 50 000.",
            reviewFocus: "Start the expanded form with the largest place value.",
            reviewFocusBm: "Mulakan bentuk cerakin dengan nilai tempat terbesar.",
          },
          "3": {
            misconceptionCode: "partition_groups_merged",
            hint: "62 307 has 0 tens and 7 ones, so the expanded form must keep those places separate.",
            hintBm: "62 307 mempunyai 0 puluh dan 7 sa, jadi bentuk cerakin mesti memisahkan tempat itu.",
            example: "In 45 003, the tens and hundreds places are both zero.",
            exampleBm: "Dalam 45 003, tempat puluh dan ratus kedua-duanya sifar.",
            reviewFocus: "Check every place appears in the expanded form.",
            reviewFocusBm: "Semak setiap tempat wujud dalam bentuk cerakin.",
          },
        },
      ],
      [
        "05",
        "What is the digit value of 7 in 62 307?",
        "Apakah nilai digit 7 dalam 62 307?",
        ["7", "70", "700", "7 000"],
        ["7", "70", "700", "7 000"],
        0,
        "Choose the value of a digit",
        "Pilih nilai bagi sesuatu digit",
        {
          "1": {
            misconceptionCode: "place_miscount",
            hint: "The 7 is the last digit of the number, so it is in the ones place.",
            hintBm: "Digit 7 ialah digit terakhir nombor, jadi ia berada di tempat sa.",
            example: "In 83 009, the 9 is worth 9.",
            exampleBm: "Dalam 83 009, digit 9 bernilai 9.",
            reviewFocus: "Look at the position of 7 in the number.",
            reviewFocusBm: "Lihat kedudukan digit 7 dalam nombor.",
          },
          "2": {
            misconceptionCode: "hundreds_value_confused",
            hint: "The 7 is not the hundreds digit. The hundreds digit in 62 307 is 3.",
            hintBm: "Digit 7 bukan digit ratus. Digit ratus dalam 62 307 ialah 3.",
            example: "In 51 207, the 7 is worth 7.",
            exampleBm: "Dalam 51 207, digit 7 bernilai 7.",
            reviewFocus: "Compare the ones place with the hundreds place.",
            reviewFocusBm: "Bandingkan tempat sa dengan tempat ratus.",
          },
          "3": {
            misconceptionCode: "thousands_value_confused",
            hint: "The thousands digit in 62 307 is 2, not 7. The 7 is the final digit.",
            hintBm: "Digit ribu dalam 62 307 ialah 2, bukan 7. Digit 7 ialah digit terakhir.",
            example: "In 40 007, the last 7 is worth 7.",
            exampleBm: "Dalam 40 007, digit 7 terakhir bernilai 7.",
            reviewFocus: "Check whether 7 is the first or last digit.",
            reviewFocusBm: "Semak sama ada 7 ialah digit pertama atau terakhir.",
          },
        },
      ],
    ],
  },
  {
    subtopicId: "compare_order_numbers",
    skillId: "y4_whole_numbers_compare_order",
    standardCode: "1.1.2 Compare and Arrange Numbers / Banding dan Susun Nombor",
    enPages: "pp. 6-8",
    bmPages: "hlm. 6-8",
    reviewFocus:
      "Line up the numbers by place value and compare from the left until a place differs.",
    reviewFocusBm:
      "Susun nombor mengikut nilai tempat dan bandingkan dari kiri sehingga satu tempat berbeza.",
    questions: [
      [
        "01",
        "Which number is greater?",
        "Nombor manakah lebih besar?",
        ["45 210", "45 120", "They are equal", "Cannot tell"],
        ["45 210", "45 120", "Kedua-duanya sama", "Tidak dapat ditentukan"],
        0,
        "Compare two numbers",
        "Bandingkan dua nombor",
        {
          "1": {
            misconceptionCode: "digit_order_swapped",
            hint: "Both numbers start with 45 thousand. Compare the hundreds digit next.",
            hintBm: "Kedua-dua nombor bermula dengan 45 ribu. Bandingkan digit ratus seterusnya.",
            example: "Between 32 810 and 32 180, 32 810 is greater.",
            exampleBm: "Antara 32 810 dengan 32 180, 32 810 lebih besar.",
            reviewFocus: "Compare digit by digit from the left.",
            reviewFocusBm: "Bandingkan digit demi digit dari kiri.",
          },
          "2": {
            misconceptionCode: "equal_place_assumed",
            hint: "The numbers have the same thousands group, but the later digits are different.",
            hintBm: "Nombor mempunyai kumpulan ribu yang sama, tetapi digit kemudian berbeza.",
            example: "66 020 and 66 200 are not equal.",
            exampleBm: "66 020 dan 66 200 tidak sama.",
            reviewFocus: "Keep comparing until a place differs.",
            reviewFocusBm: "Teruskan membanding sehingga satu tempat berbeza.",
          },
          "3": {
            misconceptionCode: "place_ignored",
            hint: "You can compare these numbers by looking at their digits place by place.",
            hintBm: "Anda boleh membandingkan nombor ini dengan melihat digit satu per satu.",
            example: "28 901 is greater than 28 109.",
            exampleBm: "28 901 lebih besar daripada 28 109.",
            reviewFocus: "Use place value to compare.",
            reviewFocusBm: "Gunakan nilai tempat untuk membandingkan.",
          },
        },
      ],
      [
        "02",
        "Choose the correct sign: 32 405 __ 32 450.",
        "Pilih tanda yang betul: 32 405 __ 32 450.",
        [">", "<", "=", "+"],
        [">", "<", "=", "+"],
        1,
        "Choose a comparison sign",
        "Pilih tanda perbandingan",
        {
          "0": {
            misconceptionCode: "hundreds_tens_swapped",
            hint: "The tens digit is 0 in 32 405 and 5 in 32 450. Compare the tens after the hundreds match.",
            hintBm: "Digit puluh ialah 0 dalam 32 405 dan 5 dalam 32 450. Bandingkan puluh selepas ratus sama.",
            example: "41 903 is less than 41 930.",
            exampleBm: "41 903 lebih kecil daripada 41 930.",
            reviewFocus: "Compare the first place that differs.",
            reviewFocusBm: "Bandingkan tempat pertama yang berbeza.",
          },
          "2": {
            misconceptionCode: "equal_place_assumed",
            hint: "The hundreds digits match, but the tens digits are 0 and 5, so the numbers are not equal.",
            hintBm: "Digit ratus sama, tetapi digit puluh ialah 0 dan 5, jadi nombor tidak sama.",
            example: "50 208 and 50 280 are different.",
            exampleBm: "50 208 dan 50 280 berbeza.",
            reviewFocus: "Check all places before choosing equal.",
            reviewFocusBm: "Semak semua tempat sebelum memilih sama.",
          },
          "3": {
            misconceptionCode: "operation_sign_confused",
            hint: "The sign asks about size, not about adding. Choose the sign that shows which number is larger.",
            hintBm: "Tanda itu bertanya tentang saiz, bukan penambahan. Pilih tanda yang menunjukkan nombor lebih besar.",
            example: "25 100 is greater than 25 010, so the sign is >.",
            exampleBm: "25 100 lebih besar daripada 25 010, jadi tandanya ialah >.",
            reviewFocus: "Compare the sizes of the two numbers.",
            reviewFocusBm: "Bandingkan saiz kedua-dua nombor.",
          },
        },
      ],
      [
        "03",
        "Which list is in ascending order?",
        "Senarai manakah dalam tertib menaik?",
        [
          "12 099, 12 909, 19 009",
          "19 009, 12 909, 12 099",
          "12 909, 12 099, 19 009",
          "19 009, 12 099, 12 909",
        ],
        [
          "12 099, 12 909, 19 009",
          "19 009, 12 909, 12 099",
          "12 909, 12 099, 19 009",
          "19 009, 12 099, 12 909",
        ],
        0,
        "Recognise ascending order",
        "Kenal tertib menaik",
        {
          "1": {
            misconceptionCode: "ascending_descending_confused",
            hint: "Ascending order starts with the smallest number and ends with the greatest.",
            hintBm: "Tertib menaik bermula dengan nombor paling kecil dan berakhir dengan paling besar.",
            example: "Ascending: 21 300, 21 900, 22 000.",
            exampleBm: "Menaik: 21 300, 21 900, 22 000.",
            reviewFocus: "Check the first number is the smallest.",
            reviewFocusBm: "Semak nombor pertama ialah paling kecil.",
          },
          "2": {
            misconceptionCode: "first_place_misread",
            hint: "12 909 is greater than 12 099 because 9 hundreds is greater than 0 hundreds.",
            hintBm: "12 909 lebih besar daripada 12 099 kerana 9 ratus lebih besar daripada 0 ratus.",
            example: "In 34 510 and 34 050, 34 510 is greater.",
            exampleBm: "Dalam 34 510 dan 34 050, 34 510 lebih besar.",
            reviewFocus: "Compare each pair in the list.",
            reviewFocusBm: "Bandingkan setiap pasangan dalam senarai.",
          },
          "3": {
            misconceptionCode: "descending_list_chosen",
            hint: "This list starts with the greatest number, so it is descending, not ascending.",
            hintBm: "Senarai ini bermula dengan nombor paling besar, jadi ia menurun, bukan menaik.",
            example: "Descending: 19 000, 18 900, 18 090.",
            exampleBm: "Menurun: 19 000, 18 900, 18 090.",
            reviewFocus: "Decide whether the list goes up or down.",
            reviewFocusBm: "Tentukan sama ada senarai naik atau turun.",
          },
        },
      ],
      [
        "04",
        "Which number is smallest?",
        "Nombor manakah paling kecil?",
        ["60 008", "6 080", "60 080", "68 000"],
        ["60 008", "6 080", "60 080", "68 000"],
        1,
        "Find the smallest number",
        "Cari nombor paling kecil",
        {
          "0": {
            misconceptionCode: "digit_count_misread",
            hint: "Compare the number of digits first. A four-digit number is smaller than a five-digit number.",
            hintBm: "Bandingkan bilangan digit dahulu. Nombor empat digit lebih kecil daripada nombor lima digit.",
            example: "7 200 is smaller than 12 000.",
            exampleBm: "7 200 lebih kecil daripada 12 000.",
            reviewFocus: "Count the digits before comparing values.",
            reviewFocusBm: "Kira digit sebelum membandingkan nilai.",
          },
          "2": {
            misconceptionCode: "zero_place_ignored",
            hint: "60 008 and 60 080 both have sixty thousands. Compare their later digits to find the smaller one.",
            hintBm: "60 008 dan 60 080 kedua-duanya mempunyai enam puluh ribu. Bandingkan digit kemudian untuk mencari yang lebih kecil.",
            example: "Between 70 002 and 70 020, 70 002 is smaller.",
            exampleBm: "Antara 70 002 dengan 70 020, 70 002 lebih kecil.",
            reviewFocus: "Compare place by place after the thousands.",
            reviewFocusBm: "Bandingkan tempat demi tempat selepas ribu.",
          },
          "3": {
            misconceptionCode: "largest_digit_confused",
            hint: "68 000 starts with a larger digit after the ten-thousands, so it is not the smallest.",
            hintBm: "68 000 bermula dengan digit yang lebih besar selepas puluh ribu, jadi ia bukan paling kecil.",
            example: "29 000 is smaller than 32 000.",
            exampleBm: "29 000 lebih kecil daripada 32 000.",
            reviewFocus: "Compare the thousands digits.",
            reviewFocusBm: "Bandingkan digit ribu.",
          },
        },
      ],
      [
        "05",
        "Which list is in descending order?",
        "Senarai manakah dalam tertib menurun?",
        [
          "88 000, 80 800, 80 080",
          "80 080, 80 800, 88 000",
          "80 800, 88 000, 80 080",
          "88 000, 80 080, 80 800",
        ],
        [
          "88 000, 80 800, 80 080",
          "80 080, 80 800, 88 000",
          "80 800, 88 000, 80 080",
          "88 000, 80 080, 80 800",
        ],
        0,
        "Recognise descending order",
        "Kenal tertib menurun",
        {
          "1": {
            misconceptionCode: "ascending_descending_confused",
            hint: "Descending order starts with the greatest number and ends with the smallest.",
            hintBm: "Tertib menurun bermula dengan nombor paling besar dan berakhir dengan paling kecil.",
            example: "Descending: 31 000, 30 900, 30 090.",
            exampleBm: "Menurun: 31 000, 30 900, 30 090.",
            reviewFocus: "Check the first number is the greatest.",
            reviewFocusBm: "Semak nombor pertama ialah paling besar.",
          },
          "2": {
            misconceptionCode: "first_place_misread",
            hint: "88 000 is greater than 80 800, so it must come before 80 800 in descending order.",
            hintBm: "88 000 lebih besar daripada 80 800, jadi ia mesti datang sebelum 80 800 dalam tertib menurun.",
            example: "In descending order, 55 000 comes before 50 500.",
            exampleBm: "Dalam tertib menurun, 55 000 datang sebelum 50 500.",
            reviewFocus: "Compare the first two numbers in the list.",
            reviewFocusBm: "Bandingkan dua nombor pertama dalam senarai.",
          },
          "3": {
            misconceptionCode: "middle_place_misread",
            hint: "80 080 is smaller than 80 800, so 80 080 must come after 80 800.",
            hintBm: "80 080 lebih kecil daripada 80 800, jadi 80 080 mesti datang selepas 80 800.",
            example: "90 090 is smaller than 90 900.",
            exampleBm: "90 090 lebih kecil daripada 90 900.",
            reviewFocus: "Check every pair is in the correct order.",
            reviewFocusBm: "Semak setiap pasangan berada dalam tertib yang betul.",
          },
        },
      ],
    ],
  },
  {
    subtopicId: "odd_even_numbers",
    skillId: "y4_whole_numbers_odd_even",
    standardCode: "1.2.1-1.2.2 Even Numbers and Odd Numbers / Nombor Genap dan Nombor Ganjil",
    enPages: "pp. 9-10",
    bmPages: "hlm. 9-10",
    reviewFocus:
      "Look at the ones digit only: even numbers end in 0, 2, 4, 6, or 8.",
    reviewFocusBm:
      "Lihat digit sa sahaja: nombor genap berakhir dengan 0, 2, 4, 6 atau 8.",
    questions: [
      [
        "01",
        "Which number is even?",
        "Nombor manakah genap?",
        ["50 204", "16 783", "64 271", "90 909"],
        ["50 204", "16 783", "64 271", "90 909"],
        0,
        "Classify a number as even",
        "Kelaskan nombor sebagai genap",
        {
          "1": {
            misconceptionCode: "ones_digit_ignored",
            hint: "Check the ones digit. An even number ends with 0, 2, 4, 6, or 8.",
            hintBm: "Semak digit sa. Nombor genap berakhir dengan 0, 2, 4, 6 atau 8.",
            example: "42 716 is even because it ends with 6.",
            exampleBm: "42 716 genap kerana berakhir dengan 6.",
            reviewFocus: "Look only at the last digit.",
            reviewFocusBm: "Lihat digit terakhir sahaja.",
          },
          "2": {
            misconceptionCode: "ones_digit_ignored",
            hint: "64 271 ends with 1, which is an odd digit.",
            hintBm: "64 271 berakhir dengan 1, iaitu digit ganjil.",
            example: "53 007 is odd because it ends with 7.",
            exampleBm: "53 007 ganjil kerana berakhir dengan 7.",
            reviewFocus: "Use the final digit to decide.",
            reviewFocusBm: "Gunakan digit akhir untuk menentukan.",
          },
          "3": {
            misconceptionCode: "ones_digit_ignored",
            hint: "90 909 ends with 9, so it is odd, not even.",
            hintBm: "90 909 berakhir dengan 9, jadi ia ganjil, bukan genap.",
            example: "38 091 is odd because it ends with 1.",
            exampleBm: "38 091 ganjil kerana berakhir dengan 1.",
            reviewFocus: "Even numbers never end with 1, 3, 5, 7, or 9.",
            reviewFocusBm: "Nombor genap tidak pernah berakhir dengan 1, 3, 5, 7 atau 9.",
          },
        },
      ],
      [
        "02",
        "Which number is odd?",
        "Nombor manakah ganjil?",
        ["50 204", "16 783", "76 000", "84 316"],
        ["50 204", "16 783", "76 000", "84 316"],
        1,
        "Classify a number as odd",
        "Kelaskan nombor sebagai ganjil",
        {
          "0": {
            misconceptionCode: "ones_digit_ignored",
            hint: "50 204 ends with 4, which is an even digit.",
            hintBm: "50 204 berakhir dengan 4, iaitu digit genap.",
            example: "60 402 is even because it ends with 2.",
            exampleBm: "60 402 genap kerana berakhir dengan 2.",
            reviewFocus: "Check the final digit.",
            reviewFocusBm: "Semak digit akhir.",
          },
          "2": {
            misconceptionCode: "zero_place_ignored",
            hint: "76 000 ends with 0, so it is even. An odd number ends with 1, 3, 5, 7, or 9.",
            hintBm: "76 000 berakhir dengan 0, jadi ia genap. Nombor ganjil berakhir dengan 1, 3, 5, 7 atau 9.",
            example: "80 000 is even because it ends with 0.",
            exampleBm: "80 000 genap kerana berakhir dengan 0.",
            reviewFocus: "Remember zero is an even digit.",
            reviewFocusBm: "Ingat sifar ialah digit genap.",
          },
          "3": {
            misconceptionCode: "ones_digit_ignored",
            hint: "84 316 ends with 6, which is an even digit.",
            hintBm: "84 316 berakhir dengan 6, iaitu digit genap.",
            example: "71 408 is even because it ends with 8.",
            exampleBm: "71 408 genap kerana berakhir dengan 8.",
            reviewFocus: "Look at the last digit only.",
            reviewFocusBm: "Lihat digit terakhir sahaja.",
          },
        },
      ],
      [
        "03",
        "Is 76 000 odd or even?",
        "Adakah 76 000 ganjil atau genap?",
        ["Odd", "Even", "Both", "Neither"],
        ["Ganjil", "Genap", "Kedua-duanya", "Tiada satu pun"],
        1,
        "Classify zero-ending numbers",
        "Kelaskan nombor berakhir sifar",
        {
          "0": {
            misconceptionCode: "zero_place_ignored",
            hint: "A number is odd only when it ends with 1, 3, 5, 7, or 9. 76 000 ends with 0.",
            hintBm: "Nombor ganjil hanya apabila berakhir dengan 1, 3, 5, 7 atau 9. 76 000 berakhir dengan 0.",
            example: "90 000 is even.",
            exampleBm: "90 000 ialah genap.",
            reviewFocus: "Zero is not an odd digit.",
            reviewFocusBm: "Sifar bukan digit ganjil.",
          },
          "2": {
            misconceptionCode: "zero_place_ignored",
            hint: "A number cannot be both odd and even. Check its ones digit once.",
            hintBm: "Nombor tidak boleh ganjil dan genap serentak. Semak digit sanya sekali.",
            example: "Every number is either odd or even.",
            exampleBm: "Setiap nombor sama ada ganjil atau genap.",
            reviewFocus: "Choose one class for the number.",
            reviewFocusBm: "Pilih satu kelas bagi nombor itu.",
          },
          "3": {
            misconceptionCode: "zero_place_ignored",
            hint: "76 000 has a ones digit, which is 0. That digit decides the class.",
            hintBm: "76 000 mempunyai digit sa, iaitu 0. Digit itu menentukan kelasnya.",
            example: "10 000 is even because it ends with 0.",
            exampleBm: "10 000 genap kerana berakhir dengan 0.",
            reviewFocus: "Every whole number is odd or even.",
            reviewFocusBm: "Setiap nombor bulat adalah ganjil atau genap.",
          },
        },
      ],
      [
        "04",
        "Which pair contains two odd numbers?",
        "Pasangan manakah mengandungi dua nombor ganjil?",
        [
          "16 783 and 64 271",
          "50 204 and 84 316",
          "76 000 and 90 909",
          "50 204 and 16 783",
        ],
        [
          "16 783 dan 64 271",
          "50 204 dan 84 316",
          "76 000 dan 90 909",
          "50 204 dan 16 783",
        ],
        0,
        "Check a pair of numbers",
        "Semak sepasang nombor",
        {
          "1": {
            misconceptionCode: "ones_digit_ignored",
            hint: "50 204 ends with 4 and 84 316 ends with 6, so both are even.",
            hintBm: "50 204 berakhir dengan 4 dan 84 316 berakhir dengan 6, jadi kedua-duanya genap.",
            example: "31 002 and 22 008 are both even.",
            exampleBm: "31 002 dan 22 008 kedua-duanya genap.",
            reviewFocus: "Check both ones digits.",
            reviewFocusBm: "Semak kedua-dua digit sa.",
          },
          "2": {
            misconceptionCode: "ones_digit_ignored",
            hint: "76 000 ends with 0, so it is even. Both numbers in the pair must be odd.",
            hintBm: "76 000 berakhir dengan 0, jadi ia genap. Kedua-dua nombor dalam pasangan mesti ganjil.",
            example: "80 100 is even because it ends with 0.",
            exampleBm: "80 100 genap kerana berakhir dengan 0.",
            reviewFocus: "Look at each ending digit.",
            reviewFocusBm: "Lihat setiap digit akhir.",
          },
          "3": {
            misconceptionCode: "ones_digit_ignored",
            hint: "50 204 ends with 4, which is even, so this pair is not two odd numbers.",
            hintBm: "50 204 berakhir dengan 4, iaitu genap, jadi pasangan ini bukan dua nombor ganjil.",
            example: "41 106 is even because it ends with 6.",
            exampleBm: "41 106 genap kerana berakhir dengan 6.",
            reviewFocus: "Every number in the pair must be odd.",
            reviewFocusBm: "Setiap nombor dalam pasangan mesti ganjil.",
          },
        },
      ],
      [
        "05",
        "Which is the first odd number after 6 020?",
        "Yang manakah nombor ganjil pertama selepas 6 020?",
        ["6 020", "6 021", "6 022", "6 030"],
        ["6 020", "6 021", "6 022", "6 030"],
        1,
        "Find the next odd number",
        "Cari nombor ganjil seterusnya",
        {
          "0": {
            misconceptionCode: "starting_value_confused",
            hint: "6 020 ends with 0, so it is even. The question asks for the number after it.",
            hintBm: "6 020 berakhir dengan 0, jadi ia genap. Soalan meminta nombor selepasnya.",
            example: "After 3 010 comes 3 011.",
            exampleBm: "Selepas 3 010 datang 3 011.",
            reviewFocus: "The next number is one more.",
            reviewFocusBm: "Nombor seterusnya ialah satu lebih.",
          },
          "2": {
            misconceptionCode: "next_even_chosen",
            hint: "6 022 ends with 2, which is even. Find the number ending in 1, 3, 5, 7, or 9.",
            hintBm: "6 022 berakhir dengan 2, iaitu genap. Cari nombor berakhir dengan 1, 3, 5, 7 atau 9.",
            example: "The first odd number after 2 010 is 2 011.",
            exampleBm: "Nombor ganjil pertama selepas 2 010 ialah 2 011.",
            reviewFocus: "Count one by one until the digit is odd.",
            reviewFocusBm: "Kira satu demi satu sehingga digit ganjil.",
          },
          "3": {
            misconceptionCode: "range_jumped",
            hint: "6 030 is ten more than 6 020. Check the numbers between them first.",
            hintBm: "6 030 ialah sepuluh lebih daripada 6 020. Semak nombor di antaranya dahulu.",
            example: "After 5 005 comes 5 006 before 5 015.",
            exampleBm: "Selepas 5 005 datang 5 006 sebelum 5 015.",
            reviewFocus: "List the numbers in order.",
            reviewFocusBm: "Senaraikan nombor mengikut tertib.",
          },
        },
      ],
    ],
  },
  {
    subtopicId: "number_patterns",
    skillId: "y4_whole_numbers_patterns",
    standardCode: "1.5.1-1.5.2 Number Patterns / Pola Nombor",
    enPages: "pp. 11-12",
    bmPages: "hlm. 11-12",
    reviewFocus:
      "Find the change between two neighbouring terms, then apply the same change once more.",
    reviewFocusBm:
      "Cari perubahan antara dua nombor yang bersebelahan, kemudian gunakan perubahan yang sama sekali lagi.",
    questions: [
      [
        "01",
        "What comes next: 20 730, 30 730, 40 730, __?",
        "Apakah seterusnya: 20 730, 30 730, 40 730, __?",
        ["50 730", "50 830", "41 730", "60 730"],
        ["50 730", "50 830", "41 730", "60 730"],
        0,
        "Continue a number pattern",
        "Sambung pola nombor",
        {
          "1": {
            misconceptionCode: "wrong_change_applied",
            hint: "Compare 20 730 and 30 730: only the ten-thousands digit changes, by 10 000.",
            hintBm: "Bandingkan 20 730 dengan 30 730: hanya digit puluh ribu berubah, sebanyak 10 000.",
            example: "After 31 500 comes 41 500 in this pattern.",
            exampleBm: "Selepas 31 500 datang 41 500 dalam pola ini.",
            reviewFocus: "Find the same change every time.",
            reviewFocusBm: "Cari perubahan yang sama setiap kali.",
          },
          "2": {
            misconceptionCode: "tens_thousands_mixed",
            hint: "40 730 increases by 10 000, so the ten-thousands digit becomes 5, not 4.",
            hintBm: "40 730 bertambah sebanyak 10 000, jadi digit puluh ribu menjadi 5, bukan 4.",
            example: "After 12 400 comes 22 400.",
            exampleBm: "Selepas 12 400 datang 22 400.",
            reviewFocus: "Apply the change to the correct digit.",
            reviewFocusBm: "Gunakan perubahan pada digit yang betul.",
          },
          "3": {
            misconceptionCode: "change_doubled",
            hint: "The pattern adds 10 000 each time, not 20 000.",
            hintBm: "Pola menambah 10 000 setiap kali, bukan 20 000.",
            example: "In 15 000, 25 000, 35 000, the change is 10 000.",
            exampleBm: "Dalam 15 000, 25 000, 35 000, perubahannya ialah 10 000.",
            reviewFocus: "Measure the change between neighbours.",
            reviewFocusBm: "Ukur perubahan antara nombor bersebelahan.",
          },
        },
      ],
      [
        "02",
        "What comes next: 88 275, 87 275, 86 275, __?",
        "Apakah seterusnya: 88 275, 87 275, 86 275, __?",
        ["85 275", "85 175", "86 175", "84 275"],
        ["85 275", "85 175", "86 175", "84 275"],
        0,
        "Continue a decreasing pattern",
        "Sambung pola menurun",
        {
          "1": {
            misconceptionCode: "wrong_digit_changed",
            hint: "Only the thousands digit changes: 88 to 87 to 86. The later digits stay the same.",
            hintBm: "Hanya digit ribu berubah: 88 kepada 87 kepada 86. Digit kemudian kekal sama.",
            example: "In 92 400, 91 400, 90 400, the hundreds stay the same.",
            exampleBm: "Dalam 92 400, 91 400, 90 400, ratus kekal sama.",
            reviewFocus: "Check which digit moves each time.",
            reviewFocusBm: "Semak digit yang bergerak setiap kali.",
          },
          "2": {
            misconceptionCode: "decrease_misapplied",
            hint: "The pattern decreases by 1 000, so the thousands digit goes down by 1.",
            hintBm: "Pola berkurang sebanyak 1 000, jadi digit ribu turun sebanyak 1.",
            example: "After 45 600 comes 44 600.",
            exampleBm: "Selepas 45 600 datang 44 600.",
            reviewFocus: "Subtract the same amount each time.",
            reviewFocusBm: "Tolak jumlah yang sama setiap kali.",
          },
          "3": {
            misconceptionCode: "change_doubled",
            hint: "The change is 1 000 each step, not 2 000.",
            hintBm: "Perubahannya ialah 1 000 setiap langkah, bukan 2 000.",
            example: "In 77 000, 76 000, 75 000, the change is 1 000.",
            exampleBm: "Dalam 77 000, 76 000, 75 000, perubahannya ialah 1 000.",
            reviewFocus: "Compare two neighbours to find the change.",
            reviewFocusBm: "Bandingkan dua nombor bersebelahan untuk mencari perubahan.",
          },
        },
      ],
      [
        "03",
        "Which rule makes 60 100, 60 110, 60 120, 60 130?",
        "Peraturan manakah menghasilkan 60 100, 60 110, 60 120, 60 130?",
        ["Add 1", "Add 10", "Add 100", "Add 1 000"],
        ["Tambah 1", "Tambah 10", "Tambah 100", "Tambah 1 000"],
        1,
        "Identify the rule of a pattern",
        "Kenal pasti peraturan pola",
        {
          "0": {
            misconceptionCode: "tens_ones_misread",
            hint: "Compare 60 100 and 60 110: the tens digit goes up by 1, which means the value grows by 10.",
            hintBm: "Bandingkan 60 100 dengan 60 110: digit puluh naik sebanyak 1, bermakna nilai bertambah 10.",
            example: "50 020, 50 030 grows by 10 each time.",
            exampleBm: "50 020, 50 030 bertambah 10 setiap kali.",
            reviewFocus: "Check which digit changes.",
            reviewFocusBm: "Semak digit yang berubah.",
          },
          "2": {
            misconceptionCode: "hundreds_place_misread",
            hint: "The hundreds digit stays 1 in every term, so the change is not 100.",
            hintBm: "Digit ratus kekal 1 dalam setiap sebutan, jadi perubahannya bukan 100.",
            example: "In 32 100, 32 200, the hundreds digit changes.",
            exampleBm: "Dalam 32 100, 32 200, digit ratus berubah.",
            reviewFocus: "Find the place that actually changes.",
            reviewFocusBm: "Cari tempat yang sebenarnya berubah.",
          },
          "3": {
            misconceptionCode: "group_value_mixed",
            hint: "The ten-thousands digit stays 6 in every term, so the change is much smaller than 1 000.",
            hintBm: "Digit puluh ribu kekal 6 dalam setiap sebutan, jadi perubahannya jauh lebih kecil daripada 1 000.",
            example: "In 40 000, 41 000, the change is 1 000.",
            exampleBm: "Dalam 40 000, 41 000, perubahannya ialah 1 000.",
            reviewFocus: "Measure the change between two terms.",
            reviewFocusBm: "Ukur perubahan antara dua sebutan.",
          },
        },
      ],
      [
        "04",
        "Fill the blank: 74 027, 74 025, 74 023, __.",
        "Isi tempat kosong: 74 027, 74 025, 74 023, __.",
        ["74 019", "74 020", "74 021", "74 022"],
        ["74 019", "74 020", "74 021", "74 022"],
        2,
        "Fill a missing pattern term",
        "Isi sebutan pola yang hilang",
        {
          "0": {
            misconceptionCode: "change_doubled",
            hint: "The pattern decreases by 2 each time: 74 027 to 74 025 to 74 023.",
            hintBm: "Pola berkurang sebanyak 2 setiap kali: 74 027 kepada 74 025 kepada 74 023.",
            example: "After 31 009, 31 007 comes 31 005.",
            exampleBm: "Selepas 31 009, 31 007 datang 31 005.",
            reviewFocus: "Use the same change each step.",
            reviewFocusBm: "Gunakan perubahan yang sama setiap langkah.",
          },
          "1": {
            misconceptionCode: "decrease_by_one",
            hint: "The change is 2, not 1: 74 025 is two less than 74 027.",
            hintBm: "Perubahannya ialah 2, bukan 1: 74 025 ialah dua kurang daripada 74 027.",
            example: "In 55 010, 55 008, the change is 2.",
            exampleBm: "Dalam 55 010, 55 008, perubahannya ialah 2.",
            reviewFocus: "Compare the first two terms.",
            reviewFocusBm: "Bandingkan dua sebutan pertama.",
          },
          "3": {
            misconceptionCode: "decrease_by_one",
            hint: "74 023 minus 2 is 74 021, not 74 022.",
            hintBm: "74 023 tolak 2 ialah 74 021, bukan 74 022.",
            example: "After 42 025, 42 023, the next term is 42 021.",
            exampleBm: "Selepas 42 025, 42 023, sebutan seterusnya ialah 42 021.",
            reviewFocus: "Subtract two from the last term.",
            reviewFocusBm: "Tolak dua daripada sebutan terakhir.",
          },
        },
      ],
      [
        "05",
        "Which sequence increases by 8?",
        "Jujukan manakah bertambah sebanyak 8?",
        [
          "81 012, 81 020, 81 028, 81 036",
          "49 383, 49 390, 49 397, 49 404",
          "81 012, 81 022, 81 032, 81 042",
          "87 527, 87 536, 87 545, 87 554",
        ],
        [
          "81 012, 81 020, 81 028, 81 036",
          "49 383, 49 390, 49 397, 49 404",
          "81 012, 81 022, 81 032, 81 042",
          "87 527, 87 536, 87 545, 87 554",
        ],
        0,
        "Identify the change in a sequence",
        "Kenal pasti perubahan dalam jujukan",
        {
          "1": {
            misconceptionCode: "change_by_seven",
            hint: "49 390 minus 49 383 is 7, not 8. Compare the first two terms of each sequence.",
            hintBm: "49 390 tolak 49 383 ialah 7, bukan 8. Bandingkan dua sebutan pertama setiap jujukan.",
            example: "In 30 005, 30 012, 30 019, the change is 7.",
            exampleBm: "Dalam 30 005, 30 012, 30 019, perubahannya ialah 7.",
            reviewFocus: "Measure the change between neighbours.",
            reviewFocusBm: "Ukur perubahan antara nombor bersebelahan.",
          },
          "2": {
            misconceptionCode: "change_by_ten",
            hint: "81 022 minus 81 012 is 10, not 8.",
            hintBm: "81 022 tolak 81 012 ialah 10, bukan 8.",
            example: "In 42 000, 42 010, 42 020, the change is 10.",
            exampleBm: "Dalam 42 000, 42 010, 42 020, perubahannya ialah 10.",
            reviewFocus: "Check the size of each step.",
            reviewFocusBm: "Semak saiz setiap langkah.",
          },
          "3": {
            misconceptionCode: "change_by_nine",
            hint: "87 536 minus 87 527 is 9, so this sequence grows by 9, not 8.",
            hintBm: "87 536 tolak 87 527 ialah 9, jadi jujukan ini bertambah 9, bukan 8.",
            example: "In 70 021, 70 030, 70 039, the change is 9.",
            exampleBm: "Dalam 70 021, 70 030, 70 039, perubahannya ialah 9.",
            reviewFocus: "Measure the first step of each sequence.",
            reviewFocusBm: "Ukur langkah pertama setiap jujukan.",
          },
        },
      ],
    ],
  },
];

function makeBank(definition) {
  const bankId = `y4_whole_${definition.subtopicId}_easy_v1`;
  const questions = definition.questions.map((item, index) => {
    const [
      suffix,
      questionText,
      questionTextBm,
      options,
      optionsBm,
      answerIndex,
      questionType,
      questionTypeBm,
      feedbackByOption,
    ] = item;
    const questionId = `q_y4_whole_${definition.subtopicId}_${suffix}`;
    return {
      id: questionId,
      bankId,
      client: {
        questionId,
        bankId,
        topicId,
        subtopicId: definition.subtopicId,
        skillId: definition.skillId,
        yearLevel: 4,
        difficultyLevel: "Easy",
        estimatedDifficulty: 0.15 + index * 0.02,
        contentVersion: CONTENT_VERSION,
        language: "bilingual",
        createdAt,
        questionText,
        questionTextBm,
        options,
        optionsBm,
        questionType,
        questionTypeBm,
        sourceMaterialId: enMaterialId,
        sourceMaterialIdBm: bmMaterialId,
        sourceLocator: `${enBook}, ${definition.standardCode}, ${definition.enPages}`,
        sourceLocatorBm: `${bmBook}, ${definition.standardCode}, ${definition.bmPages}`,
        sourceSectionClass: "exercise",
        sectionJustification: "",
        isActive: true,
        order: index + 1,
      },
      answerKey: {
        questionId,
        answerIndex,
        feedbackByOption,
        difficultyReview: {
          cognitiveDemand: "direct_recall",
          reasoningStepCount: 1,
          transferRequired: false,
        },
        contentVersion: CONTENT_VERSION,
        createdAt,
        isActive: true,
        sourceMaterialId: enMaterialId,
        sourceMaterialIdBm: bmMaterialId,
        authorId: AUTHOR_ID,
        reviewerId: REVIEWER_ID,
        approvedAt: APPROVED_AT,
      },
    };
  });
  return {
    bank: {
      bankId,
      topicId,
      subtopicId: definition.subtopicId,
      skillId: definition.skillId,
      yearLevel: 4,
      difficultyLevel: "Easy",
      questionIds: questions.map((item) => item.id),
      version: CONTENT_VERSION,
      isActive: true,
      sourceMaterialId: enMaterialId,
      sourceMaterialIdBm: bmMaterialId,
    },
    questions,
  };
}

const built = definitions.map(makeBank);
const questionBanks = Object.fromEntries(built.map(({ bank }) => [bank.bankId, bank]));
const questions = built.flatMap(({ questions }) => questions);

function validateAdditionalQuestionBanks() {
  for (const bank of Object.values(questionBanks)) {
    if (bank.questionIds.length !== 5) {
      throw new Error(`Invalid bank ${bank.bankId}: expected exactly five questions.`);
    }
  }
}

module.exports = { questionBanks, questions, validateAdditionalQuestionBanks };
