// Year 6 Whole Numbers - Read and Say Numbers (1.1.1).
// Source-grounded in MATHEMATICS Y6 SK (SEMAKAN 2017).pdf (pp. 8-10) and
// MATEMATIK T6 SK (SEMAKAN 2017) - PART 1.pdf: numbers up to 10 000 000.
const {
  CONTENT_VERSION,
  AUTHOR_ID,
  REVIEWER_ID,
  APPROVED_AT,
} = require("./content_source_manifest");

const topicId = "whole_numbers_y6";
const subtopicId = "read_write_numbers";
const skillId = "y6_whole_numbers_read_write";
const createdAt = "2026-08-12T00:00:00Z";
const enMaterialId = "en_y6";
const bmMaterialId = "bm_y6_1";
const enBook = "MATHEMATICS Y6 SK (SEMAKAN 2017)";
const bmBook = "MATEMATIK T6 SK (SEMAKAN 2017) - PART 1";
const standardCode = "1.1.1 Read and Say Numbers / Baca dan Sebut Nombor";
const sectionClass = "exercise";

const bankIdFor = (difficulty) =>
  `y6_whole_read_write_${difficulty.toLowerCase()}_v1`;

function question(
  suffix,
  difficulty,
  estimatedDifficulty,
  questionText,
  questionTextBm,
  options,
  optionsBm,
  answerIndex,
  meta,
) {
  const questionId = `q_y6_whole_read_write_${suffix}`;
  const order = Number(suffix.slice(-2)) - 1;
  return {
    id: questionId,
    bankId: bankIdFor(difficulty),
    client: {
      questionId,
      bankId: bankIdFor(difficulty),
      topicId,
      subtopicId,
      skillId,
      yearLevel: 6,
      difficultyLevel: difficulty,
      estimatedDifficulty,
      contentVersion: CONTENT_VERSION,
      language: "bilingual",
      createdAt,
      order,
      questionText,
      questionTextBm,
      options,
      optionsBm,
      questionType: meta.questionType,
      questionTypeBm: meta.questionTypeBm,
      sourceMaterialId: enMaterialId,
      sourceMaterialIdBm: bmMaterialId,
      sourceLocator: meta.sourceLocator,
      sourceLocatorBm: meta.sourceLocatorBm,
      sourceSectionClass: meta.sourceSectionClass ?? sectionClass,
      sectionJustification: meta.sectionJustification ?? "",
      isActive: true,
    },
    answerKey: {
      questionId,
      answerIndex,
      feedbackByOption: meta.feedbackByOption,
      difficultyReview: meta.difficultyReview,
      contentVersion: CONTENT_VERSION,
      createdAt,
      isActive: true,
      sourceMaterialId: enMaterialId,
      sourceMaterialIdBm: bmMaterialId,
      authorId: AUTHOR_ID,
      reviewerId: REVIEWER_ID,
      approvedAt: APPROVED_AT,
    },
  };
}

const questions = [
  question(
    "easy_01",
    "Easy",
    0.15,
    "Which numeral shows one million two hundred thirty-seven thousand four hundred and eighty-three?",
    "Angka manakah menunjukkan satu juta dua ratus tiga puluh tujuh ribu empat ratus lapan puluh tiga?",
    ["1 237 483", "1 237 843", "1 273 483", "12 374 830"],
    ["1 237 483", "1 237 843", "1 273 483", "12 374 830"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 8`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 8`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is four hundred and eighty-three: 483, not 843.",
          hintBm: "Hujungnya ialah empat ratus lapan puluh tiga: 483, bukan 843.",
          example: "In 2 316 594, the ending 594 is five hundred ninety-four.",
          exampleBm: "Dalam 2 316 594, hujung 594 ialah lima ratus sembilan puluh empat.",
          reviewFocus: "Read the last three digits as a group.",
          reviewFocusBm: "Baca tiga digit terakhir sebagai satu kumpulan.",
        },
        "2": {
          misconceptionCode: "digit_group_swap",
          hint: "The thousands group is two hundred thirty-seven, so the middle digits are 237.",
          hintBm: "Kumpulan ribu ialah dua ratus tiga puluh tujuh, jadi digit tengah ialah 237.",
          example: "In 4 512 000, the thousands group is 512.",
          exampleBm: "Dalam 4 512 000, kumpulan ribu ialah 512.",
          reviewFocus: "Keep the thousands group in order.",
          reviewFocusBm: "Kekalkan kumpulan ribu mengikut tertib.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "One million has seven digits. Count the digits before choosing.",
          hintBm: "Satu juta mempunyai tujuh digit. Kira digit sebelum memilih.",
          example: "In 2 000 000, there are seven digits.",
          exampleBm: "Dalam 2 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the number of digits.",
          reviewFocusBm: "Semak bilangan digit.",
        },
      },
    },
  ),
  question(
    "easy_02",
    "Easy",
    0.15,
    "Which number is written as 7 290 005?",
    "Nombor manakah ditulis sebagai 7 290 005?",
    [
      "seven million two hundred ninety thousand and five",
      "seven million two hundred nine thousand and five",
      "seven hundred twenty-nine thousand and five",
      "seven million two hundred ninety thousand fifty",
    ],
    [
      "tujuh juta dua ratus sembilan puluh ribu lima",
      "tujuh juta dua ratus sembilan ribu lima",
      "tujuh ratus dua puluh sembilan ribu lima",
      "tujuh juta dua ratus sembilan puluh ribu lima puluh",
    ],
    0,
    {
      questionType: "Read a numeral in words",
      questionTypeBm: "Baca angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 290: two hundred and ninety, not two hundred and nine.",
          hintBm: "Kumpulan ribu ialah 290: dua ratus sembilan puluh, bukan dua ratus sembilan.",
          example: "In 6 480 000, the thousands group is 480.",
          exampleBm: "Dalam 6 480 000, kumpulan ribu ialah 480.",
          reviewFocus: "Read the whole thousands group.",
          reviewFocusBm: "Baca keseluruhan kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "millions_dropped",
          hint: "The number has seven million, so the words must start with seven million.",
          hintBm: "Nombor mempunyai tujuh juta, jadi perkataan mesti bermula dengan tujuh juta.",
          example: "In 5 100 000, the words start with five million.",
          exampleBm: "Dalam 5 100 000, perkataan bermula dengan lima juta.",
          reviewFocus: "Name the millions group first.",
          reviewFocusBm: "Sebut kumpulan juta dahulu.",
        },
        "3": {
          misconceptionCode: "tens_ones_misread",
          hint: "The ending is 005: five in the ones place, not fifty.",
          hintBm: "Hujungnya ialah 005: lima di tempat sa, bukan lima puluh.",
          example: "In 8 100 007, the ending 007 is seven.",
          exampleBm: "Dalam 8 100 007, hujung 007 ialah tujuh.",
          reviewFocus: "Read the last three digits carefully.",
          reviewFocusBm: "Baca tiga digit terakhir dengan teliti.",
        },
      },
    },
  ),
  question(
    "easy_03",
    "Easy",
    0.18,
    "Write three million five hundred four thousand and thirteen in numerals.",
    "Tulis tiga juta lima ratus empat ribu tiga belas dalam angka.",
    ["3 504 013", "3 504 130", "3 540 013", "350 413"],
    ["3 504 013", "3 504 130", "3 540 013", "350 413"],
    0,
    {
      questionType: "Write a number in words as numerals",
      questionTypeBm: "Tulis nombor dalam perkataan sebagai angka",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is thirteen, so the last three digits are 013, not 130.",
          hintBm: "Hujungnya ialah tiga belas, jadi tiga digit terakhir ialah 013, bukan 130.",
          example: "In 2 400 019, the ending 019 is nineteen.",
          exampleBm: "Dalam 2 400 019, hujung 019 ialah sembilan belas.",
          reviewFocus: "Place thirteen in the tens and ones places.",
          reviewFocusBm: "Letakkan tiga belas di tempat puluh dan sa.",
        },
        "2": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is five hundred and four, so the middle digits are 504, not 540.",
          hintBm: "Kumpulan ribu ialah lima ratus empat, jadi digit tengah ialah 504, bukan 540.",
          example: "In 6 702 000, the thousands group is 702.",
          exampleBm: "Dalam 6 702 000, kumpulan ribu ialah 702.",
          reviewFocus: "Keep the zero in the tens place of the thousands group.",
          reviewFocusBm: "Kekalkan sifar di tempat puluh dalam kumpulan ribu.",
        },
        "3": {
          misconceptionCode: "millions_dropped",
          hint: "Three million needs seven digits. The number must start with 3 followed by six digits.",
          hintBm: "Tiga juta memerlukan tujuh digit. Nombor mesti bermula dengan 3 diikuti enam digit.",
          example: "In 4 000 000, there are seven digits.",
          exampleBm: "Dalam 4 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the digit count.",
          reviewFocusBm: "Semak bilangan digit.",
        },
      },
    },
  ),
  question(
    "easy_04",
    "Easy",
    0.18,
    "Which words match 8 000 080?",
    "Perkataan manakah sepadan dengan 8 000 080?",
    [
      "eight million and eighty",
      "eight million and eight",
      "eight hundred thousand and eighty",
      "eighty million and eighty",
    ],
    [
      "lapan juta lapan puluh",
      "lapan juta lapan",
      "lapan ratus ribu lapan puluh",
      "lapan puluh juta lapan puluh",
    ],
    0,
    {
      questionType: "Write a numeral in words",
      questionTypeBm: "Tulis angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_misread",
          hint: "The 8 is in the tens place, so the number ends with eighty, not eight.",
          hintBm: "Digit 8 berada di tempat puluh, jadi nombor berakhir dengan lapan puluh, bukan lapan.",
          example: "In 7 000 050, the ending 050 is fifty.",
          exampleBm: "Dalam 7 000 050, hujung 050 ialah lima puluh.",
          reviewFocus: "Check the last two digits.",
          reviewFocusBm: "Semak dua digit terakhir.",
        },
        "2": {
          misconceptionCode: "millions_dropped",
          hint: "The 8 is in the millions place, so the words start with eight million.",
          hintBm: "Digit 8 berada di tempat juta, jadi perkataan bermula dengan lapan juta.",
          example: "In 9 000 000, the words start with nine million.",
          exampleBm: "Dalam 9 000 000, perkataan bermula dengan sembilan juta.",
          reviewFocus: "Name the millions place first.",
          reviewFocusBm: "Sebut tempat juta dahulu.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "8 000 080 has seven digits, so it is eight million, not eighty million or eight hundred thousand.",
          hintBm: "8 000 080 mempunyai tujuh digit, jadi ia ialah lapan juta, bukan lapan puluh juta atau lapan ratus ribu.",
          example: "In 8 000 000, there are seven digits.",
          exampleBm: "Dalam 8 000 000, terdapat tujuh digit.",
          reviewFocus: "Count the digits before reading.",
          reviewFocusBm: "Kira digit sebelum membaca.",
        },
      },
    },
  ),
  question(
    "easy_05",
    "Easy",
    0.2,
    "Which numeral matches six million three thousand nine hundred and seven?",
    "Angka manakah sepadan dengan enam juta tiga ribu sembilan ratus tujuh?",
    ["6 003 907", "6 030 907", "6 003 970", "6 300 907"],
    ["6 003 907", "6 030 907", "6 003 970", "6 300 907"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_thousands_skipped",
          hint: "There are three thousands, not thirty. Keep the zero in the ten-thousands place.",
          hintBm: "Terdapat tiga ribu, bukan tiga puluh ribu. Kekalkan sifar di tempat puluh ribu.",
          example: "In 5 002 000, the thousands group is 002.",
          exampleBm: "Dalam 5 002 000, kumpulan ribu ialah 002.",
          reviewFocus: "Keep the middle groups in place.",
          reviewFocusBm: "Kekalkan kumpulan tengah pada tempatnya.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is nine hundred and seven: 907, not 970.",
          hintBm: "Hujungnya ialah sembilan ratus tujuh: 907, bukan 970.",
          example: "In 4 001 308, the ending 308 is three hundred and eight.",
          exampleBm: "Dalam 4 001 308, hujung 308 ialah tiga ratus lapan.",
          reviewFocus: "Read the last three digits in order.",
          reviewFocusBm: "Baca tiga digit terakhir mengikut tertib.",
        },
        "3": {
          misconceptionCode: "digit_group_swap",
          hint: "The thousands group is 003, so the middle digits are 003, not 300.",
          hintBm: "Kumpulan ribu ialah 003, jadi digit tengah ialah 003, bukan 300.",
          example: "In 2 007 000, the thousands group is 007.",
          exampleBm: "Dalam 2 007 000, kumpulan ribu ialah 007.",
          reviewFocus: "Match the groups with the words.",
          reviewFocusBm: "Padankan kumpulan dengan perkataan.",
        },
      },
    },
  ),
  question(
    "moderate_01",
    "Moderate",
    0.45,
    "A card says 5 015 078. Which sentence reads it correctly?",
    "Kad menunjukkan 5 015 078. Ayat manakah membacanya dengan betul?",
    [
      "five million fifteen thousand and seventy-eight",
      "five million one hundred fifty thousand and seventy-eight",
      "five hundred fifteen thousand and seventy-eight",
      "fifty million fifteen thousand and seventy-eight",
    ],
    [
      "lima juta lima belas ribu tujuh puluh lapan",
      "lima juta seratus lima puluh ribu tujuh puluh lapan",
      "lima ratus lima belas ribu tujuh puluh lapan",
      "lima puluh juta lima belas ribu tujuh puluh lapan",
    ],
    0,
    {
      questionType: "Read a numeral in words",
      questionTypeBm: "Baca angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "hundred_thousands_added",
          hint: "The thousands group is 015: fifteen thousand, not one hundred fifty thousand.",
          hintBm: "Kumpulan ribu ialah 015: lima belas ribu, bukan seratus lima puluh ribu.",
          example: "In 3 027 000, the thousands group is 027.",
          exampleBm: "Dalam 3 027 000, kumpulan ribu ialah 027.",
          reviewFocus: "Read the zero hundred-thousands digit.",
          reviewFocusBm: "Baca digit ratus ribu sifar.",
        },
        "2": {
          misconceptionCode: "millions_dropped",
          hint: "The number has five million, so the words must start with five million.",
          hintBm: "Nombor mempunyai lima juta, jadi perkataan mesti bermula dengan lima juta.",
          example: "In 6 100 000, the words start with six million.",
          exampleBm: "Dalam 6 100 000, perkataan bermula dengan enam juta.",
          reviewFocus: "Name the millions group first.",
          reviewFocusBm: "Sebut kumpulan juta dahulu.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "5 015 078 has seven digits. Fifty million has eight digits.",
          hintBm: "5 015 078 mempunyai tujuh digit. Lima puluh juta mempunyai lapan digit.",
          example: "In 5 000 000, there are seven digits.",
          exampleBm: "Dalam 5 000 000, terdapat tujuh digit.",
          reviewFocus: "Count the digits before reading.",
          reviewFocusBm: "Kira digit sebelum membaca.",
        },
      },
    },
  ),
  question(
    "moderate_02",
    "Moderate",
    0.45,
    "Which numeral represents eight million seven hundred fifty thousand and forty-three?",
    "Angka manakah mewakili lapan juta tujuh ratus lima puluh ribu empat puluh tiga?",
    ["8 750 043", "8 705 043", "8 750 403", "875 043"],
    ["8 750 043", "8 705 043", "8 750 403", "875 043"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 750: seven hundred and fifty, not seven hundred and five.",
          hintBm: "Kumpulan ribu ialah 750: tujuh ratus lima puluh, bukan tujuh ratus lima.",
          example: "In 4 830 000, the thousands group is 830.",
          exampleBm: "Dalam 4 830 000, kumpulan ribu ialah 830.",
          reviewFocus: "Read the whole thousands group.",
          reviewFocusBm: "Baca keseluruhan kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is forty-three: 043, not 403.",
          hintBm: "Hujungnya ialah empat puluh tiga: 043, bukan 403.",
          example: "In 9 001 026, the ending 026 is twenty-six.",
          exampleBm: "Dalam 9 001 026, hujung 026 ialah dua puluh enam.",
          reviewFocus: "Place forty-three in the tens and ones.",
          reviewFocusBm: "Letakkan empat puluh tiga di tempat puluh dan sa.",
        },
        "3": {
          misconceptionCode: "millions_dropped",
          hint: "Eight million needs seven digits. The number must start with 8 followed by six digits.",
          hintBm: "Lapan juta memerlukan tujuh digit. Nombor mesti bermula dengan 8 diikuti enam digit.",
          example: "In 8 000 000, there are seven digits.",
          exampleBm: "Dalam 8 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the digit count.",
          reviewFocusBm: "Semak bilangan digit.",
        },
      },
    },
  ),
  question(
    "moderate_03",
    "Moderate",
    0.48,
    "Which words match 4 000 302?",
    "Perkataan manakah sepadan dengan 4 000 302?",
    [
      "four million three hundred and two",
      "four million three hundred and twenty",
      "four hundred thousand three hundred and two",
      "forty million three hundred and two",
    ],
    [
      "empat juta tiga ratus dua",
      "empat juta tiga ratus dua puluh",
      "empat ratus ribu tiga ratus dua",
      "empat puluh juta tiga ratus dua",
    ],
    0,
    {
      questionType: "Write a numeral in words",
      questionTypeBm: "Tulis angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_misread",
          hint: "The ending is 302: three hundred and two, not three hundred and twenty.",
          hintBm: "Hujungnya ialah 302: tiga ratus dua, bukan tiga ratus dua puluh.",
          example: "In 5 000 106, the ending 106 is one hundred and six.",
          exampleBm: "Dalam 5 000 106, hujung 106 ialah seratus enam.",
          reviewFocus: "Check the tens digit of the ending.",
          reviewFocusBm: "Semak digit puluh pada hujung.",
        },
        "2": {
          misconceptionCode: "millions_dropped",
          hint: "The 4 is in the millions place, so the words start with four million.",
          hintBm: "Digit 4 berada di tempat juta, jadi perkataan bermula dengan empat juta.",
          example: "In 4 000 000, the words start with four million.",
          exampleBm: "Dalam 4 000 000, perkataan bermula dengan empat juta.",
          reviewFocus: "Name the millions place first.",
          reviewFocusBm: "Sebut tempat juta dahulu.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "4 000 302 has seven digits. Forty million has eight digits.",
          hintBm: "4 000 302 mempunyai tujuh digit. Empat puluh juta mempunyai lapan digit.",
          example: "In 4 000 000, there are seven digits.",
          exampleBm: "Dalam 4 000 000, terdapat tujuh digit.",
          reviewFocus: "Count the digits before reading.",
          reviewFocusBm: "Kira digit sebelum membaca.",
        },
      },
    },
  ),
  question(
    "moderate_04",
    "Moderate",
    0.48,
    "Write five million five hundred three thousand three hundred and sixty-one in numerals.",
    "Tulis lima juta lima ratus tiga ribu tiga ratus enam puluh satu dalam angka.",
    ["5 503 361", "5 530 361", "5 503 631", "5 053 361"],
    ["5 503 361", "5 530 361", "5 503 631", "5 053 361"],
    0,
    {
      questionType: "Write a number in words as numerals",
      questionTypeBm: "Tulis nombor dalam perkataan sebagai angka",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is five hundred and three, so the middle digits are 503, not 530.",
          hintBm: "Kumpulan ribu ialah lima ratus tiga, jadi digit tengah ialah 503, bukan 530.",
          example: "In 6 704 000, the thousands group is 704.",
          exampleBm: "Dalam 6 704 000, kumpulan ribu ialah 704.",
          reviewFocus: "Keep the zero in the tens place of the thousands group.",
          reviewFocusBm: "Kekalkan sifar di tempat puluh dalam kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "hundreds_tens_swapped",
          hint: "The ending is three hundred and sixty-one: 361, not 631.",
          hintBm: "Hujungnya ialah tiga ratus enam puluh satu: 361, bukan 631.",
          example: "In 2 100 542, the ending 542 is five hundred forty-two.",
          exampleBm: "Dalam 2 100 542, hujung 542 ialah lima ratus empat puluh dua.",
          reviewFocus: "Read the last three digits in order.",
          reviewFocusBm: "Baca tiga digit terakhir mengikut tertib.",
        },
        "3": {
          misconceptionCode: "zero_ten_thousands_skipped",
          hint: "There are zero ten-thousands, so the second digit must be 0.",
          hintBm: "Terdapat sifar puluh ribu, jadi digit kedua mesti 0.",
          example: "In 7 005 000, the second digit is 0.",
          exampleBm: "Dalam 7 005 000, digit kedua ialah 0.",
          reviewFocus: "Write every place in order.",
          reviewFocusBm: "Tulis setiap tempat mengikut tertib.",
        },
      },
    },
  ),
  question(
    "moderate_05",
    "Moderate",
    0.5,
    "Which number has 7 millions, 0 hundred-thousands, 0 ten-thousands, 0 thousands, 9 hundreds, 1 ten, and 9 ones?",
    "Nombor manakah mempunyai 7 juta, 0 ratus ribu, 0 puluh ribu, 0 ribu, 9 ratus, 1 puluh dan 9 sa?",
    ["7 000 919", "7 009 190", "7 090 919", "700 919"],
    ["7 000 919", "7 009 190", "7 090 919", "700 919"],
    0,
    {
      questionType: "Build a number from place values",
      questionTypeBm: "Bina nombor daripada nilai tempat",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_places_skipped",
          hint: "The thousands groups are all zero, so the middle digits are 000, then 9 hundreds, 1 ten, 9 ones.",
          hintBm: "Kumpulan ribu semuanya sifar, jadi digit tengah ialah 000, kemudian 9 ratus, 1 puluh, 9 sa.",
          example: "In 6 000 100, the middle is 000 and the ending is 100.",
          exampleBm: "Dalam 6 000 100, tengahnya ialah 000 dan hujungnya ialah 100.",
          reviewFocus: "Keep the zero thousands groups.",
          reviewFocusBm: "Kekalkan kumpulan ribu sifar.",
        },
        "2": {
          misconceptionCode: "ten_thousands_added",
          hint: "The 9 is in the hundreds place, not the ten-thousands place.",
          hintBm: "Digit 9 berada di tempat ratus, bukan di tempat puluh ribu.",
          example: "In 5 000 700, the 7 is in the hundreds place.",
          exampleBm: "Dalam 5 000 700, digit 7 berada di tempat ratus.",
          reviewFocus: "Place the hundreds digit correctly.",
          reviewFocusBm: "Letakkan digit ratus dengan betul.",
        },
        "3": {
          misconceptionCode: "millions_dropped",
          hint: "Seven million needs seven digits, so the number starts with 7 followed by six digits.",
          hintBm: "Tujuh juta memerlukan tujuh digit, jadi nombor bermula dengan 7 diikuti enam digit.",
          example: "In 7 000 000, there are seven digits.",
          exampleBm: "Dalam 7 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the digit count.",
          reviewFocusBm: "Semak bilangan digit.",
        },
      },
    },
  ),
  question(
    "hard_01",
    "Hard",
    0.75,
    "Which number-word pair does not match?",
    "Pasangan nombor-perkataan manakah tidak sepadan?",
    [
      "1 892 342 - one million eight hundred ninety-two thousand three hundred and forty-two",
      "2 734 180 - two million seven hundred thirty-four thousand one hundred and eighty",
      "2 384 520 - two million three hundred eighty-four thousand five hundred and twenty",
      "9 311 200 - nine hundred thirty-one thousand one hundred and twenty",
    ],
    [
      "1 892 342 - satu juta lapan ratus sembilan puluh dua ribu tiga ratus empat puluh dua",
      "2 734 180 - dua juta tujuh ratus tiga puluh empat ribu seratus lapan puluh",
      "2 384 520 - dua juta tiga ratus lapan puluh empat ribu lima ratus dua puluh",
      "9 311 200 - sembilan ratus tiga puluh satu ribu seratus dua puluh",
    ],
    3,
    {
      questionType: "Check number-word pairs",
      questionTypeBm: "Semak pasangan nombor-perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "0": {
          misconceptionCode: "pair_misread",
          hint: "1 892 342 has one million and eight hundred ninety-two thousands. Check that every pair reads the same groups.",
          hintBm: "1 892 342 mempunyai satu juta dan lapan ratus sembilan puluh dua ribu. Semak setiap pasangan membaca kumpulan yang sama.",
          example: "In 3 241 507, the groups are 3, 241, and 507.",
          exampleBm: "Dalam 3 241 507, kumpulannya ialah 3, 241 dan 507.",
          reviewFocus: "Compare the millions and thousands groups.",
          reviewFocusBm: "Bandingkan kumpulan juta dan ribu.",
        },
        "1": {
          misconceptionCode: "pair_misread",
          hint: "2 734 180 has two million and seven hundred thirty-four thousands.",
          hintBm: "2 734 180 mempunyai dua juta dan tujuh ratus tiga puluh empat ribu.",
          example: "In 5 620 009, the groups are 5, 620, and 009.",
          exampleBm: "Dalam 5 620 009, kumpulannya ialah 5, 620 dan 009.",
          reviewFocus: "Read each group of three digits.",
          reviewFocusBm: "Baca setiap kumpulan tiga digit.",
        },
        "2": {
          misconceptionCode: "pair_misread",
          hint: "2 384 520 has two million and three hundred eighty-four thousands.",
          hintBm: "2 384 520 mempunyai dua juta dan tiga ratus lapan puluh empat ribu.",
          example: "In 4 902 100, the groups are 4, 902, and 100.",
          exampleBm: "Dalam 4 902 100, kumpulannya ialah 4, 902 dan 100.",
          reviewFocus: "Check the thousands group in each pair.",
          reviewFocusBm: "Semak kumpulan ribu dalam setiap pasangan.",
        },
      },
    },
  ),
  question(
    "hard_02",
    "Hard",
    0.75,
    "Which number has the same wording pattern as 8 000 080?",
    "Nombor manakah mempunyai pola bacaan yang sama seperti 8 000 080?",
    ["9 000 050", "9 000 500", "9 005 000", "900 050"],
    ["9 000 050", "9 000 500", "9 005 000", "900 050"],
    0,
    {
      questionType: "Compare wording patterns",
      questionTypeBm: "Bandingkan pola bacaan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_place_shift",
          hint: "8 000 080 ends with eighty in the tens place and zeros everywhere else. The ending must be 050, not 500.",
          hintBm: "8 000 080 berakhir dengan lapan puluh di tempat puluh dan sifar di tempat lain. Hujungnya mesti 050, bukan 500.",
          example: "In 7 000 060, the ending 060 is sixty.",
          exampleBm: "Dalam 7 000 060, hujung 060 ialah enam puluh.",
          reviewFocus: "Compare the last three digits.",
          reviewFocusBm: "Bandingkan tiga digit terakhir.",
        },
        "2": {
          misconceptionCode: "zero_place_shift",
          hint: "8 000 080 has zeros in the thousands groups. 9 005 000 has a five in the thousands group.",
          hintBm: "8 000 080 mempunyai sifar dalam kumpulan ribu. 9 005 000 mempunyai lima dalam kumpulan ribu.",
          example: "In 6 000 030, the thousands groups are zero.",
          exampleBm: "Dalam 6 000 030, kumpulan ribu ialah sifar.",
          reviewFocus: "Check the middle groups are zero.",
          reviewFocusBm: "Semak kumpulan tengah ialah sifar.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "8 000 080 has seven digits. Count the digits of each option.",
          hintBm: "8 000 080 mempunyai tujuh digit. Kira digit setiap pilihan.",
          example: "In 9 000 000, there are seven digits.",
          exampleBm: "Dalam 9 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the number of digits first.",
          reviewFocusBm: "Semak bilangan digit dahulu.",
        },
      },
    },
  ),
  question(
    "hard_03",
    "Hard",
    0.78,
    "A pupil writes 3 504 013 as three million five hundred four thousand one hundred and thirty. What is the best correction?",
    "Murid menulis 3 504 013 sebagai tiga juta lima ratus empat ribu seratus tiga puluh. Apakah pembetulan terbaik?",
    [
      "It should be three million five hundred four thousand and thirteen.",
      "It should be three million five hundred forty thousand and thirteen.",
      "It should be three million five hundred four thousand and thirty.",
      "It should be thirty million five hundred four thousand and thirteen.",
    ],
    [
      "Sepatutnya tiga juta lima ratus empat ribu tiga belas.",
      "Sepatutnya tiga juta lima ratus empat puluh ribu tiga belas.",
      "Sepatutnya tiga juta lima ratus empat ribu tiga puluh.",
      "Sepatutnya tiga puluh juta lima ratus empat ribu tiga belas.",
    ],
    0,
    {
      questionType: "Correct a number written in words",
      questionTypeBm: "Betulkan nombor yang ditulis dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "multi_step",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 504: five hundred and four, not five hundred and forty.",
          hintBm: "Kumpulan ribu ialah 504: lima ratus empat, bukan lima ratus empat puluh.",
          example: "In 6 703 000, the thousands group is 703.",
          exampleBm: "Dalam 6 703 000, kumpulan ribu ialah 703.",
          reviewFocus: "Keep the zero in the tens place of the thousands group.",
          reviewFocusBm: "Kekalkan sifar di tempat puluh dalam kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is 013: thirteen, not thirty.",
          hintBm: "Hujungnya ialah 013: tiga belas, bukan tiga puluh.",
          example: "In 2 400 019, the ending 019 is nineteen.",
          exampleBm: "Dalam 2 400 019, hujung 019 ialah sembilan belas.",
          reviewFocus: "Check the last two digits.",
          reviewFocusBm: "Semak dua digit terakhir.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "Three million needs seven digits, so the number starts with 3, not 30.",
          hintBm: "Tiga juta memerlukan tujuh digit, jadi nombor bermula dengan 3, bukan 30.",
          example: "In 3 000 000, there are seven digits.",
          exampleBm: "Dalam 3 000 000, terdapat tujuh digit.",
          reviewFocus: "Check the first digit is the millions digit.",
          reviewFocusBm: "Semak digit pertama ialah digit juta.",
        },
      },
    },
  ),
  question(
    "hard_04",
    "Hard",
    0.78,
    "Which number fits: 6 millions, 0 hundred-thousands, 0 ten-thousands, 3 thousands, 9 hundreds, 0 tens, 7 ones?",
    "Nombor manakah sepadan: 6 juta, 0 ratus ribu, 0 puluh ribu, 3 ribu, 9 ratus, 0 puluh, 7 sa?",
    ["6 003 907", "6 300 907", "6 003 970", "6 039 007"],
    ["6 003 907", "6 300 907", "6 003 970", "6 039 007"],
    0,
    {
      questionType: "Build a number from place values",
      questionTypeBm: "Bina nombor daripada nilai tempat",
      sourceLocator: `${enBook}, ${standardCode}, p. 10`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "multi_step",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_places_skipped",
          hint: "The hundred-thousands and ten-thousands places are zero, so the middle starts 00, then 3 thousands.",
          hintBm: "Tempat ratus ribu dan puluh ribu ialah sifar, jadi tengah bermula 00, kemudian 3 ribu.",
          example: "In 5 002 000, the middle is 002.",
          exampleBm: "Dalam 5 002 000, tengahnya ialah 002.",
          reviewFocus: "Write the zero places before the thousands.",
          reviewFocusBm: "Tulis tempat sifar sebelum ribu.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The tens digit is 0 and the ones digit is 7, so the ending is 907, not 970.",
          hintBm: "Digit puluh ialah 0 dan digit sa ialah 7, jadi hujungnya ialah 907, bukan 970.",
          example: "In 4 001 205, the ending 205 is two hundred and five.",
          exampleBm: "Dalam 4 001 205, hujung 205 ialah dua ratus lima.",
          reviewFocus: "Keep the zero tens digit.",
          reviewFocusBm: "Kekalkan digit puluh sifar.",
        },
        "3": {
          misconceptionCode: "ten_thousands_added",
          hint: "The 3 is in the thousands place, not the ten-thousands place.",
          hintBm: "Digit 3 berada di tempat ribu, bukan di tempat puluh ribu.",
          example: "In 6 003 000, the 3 is in the thousands place.",
          exampleBm: "Dalam 6 003 000, digit 3 berada di tempat ribu.",
          reviewFocus: "Place the thousands digit correctly.",
          reviewFocusBm: "Letakkan digit ribu dengan betul.",
        },
      },
    },
  ),
  question(
    "hard_05",
    "Hard",
    0.8,
    "Which statement correctly compares 7 290 005 and 7 209 005?",
    "Pernyataan manakah membandingkan 7 290 005 dan 7 209 005 dengan betul?",
    [
      "7 290 005 is greater because it has 9 ten-thousands.",
      "7 209 005 is greater because it has 9 ten-thousands.",
      "They are equal.",
      "7 290 005 has fewer digits.",
    ],
    [
      "7 290 005 lebih besar kerana mempunyai 9 puluh ribu.",
      "7 209 005 lebih besar kerana mempunyai 9 puluh ribu.",
      "Kedua-duanya sama.",
      "7 290 005 mempunyai bilangan digit yang lebih sedikit.",
    ],
    0,
    {
      questionType: "Compare two numbers",
      questionTypeBm: "Bandingkan dua nombor",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "digit_order_swapped",
          hint: "7 290 005 has 9 ten-thousands; 7 209 005 has 0 ten-thousands. Compare the ten-thousands place.",
          hintBm: "7 290 005 mempunyai 9 puluh ribu; 7 209 005 mempunyai 0 puluh ribu. Bandingkan tempat puluh ribu.",
          example: "Between 6 310 000 and 6 130 000, 6 310 000 is greater.",
          exampleBm: "Antara 6 310 000 dan 6 130 000, 6 310 000 lebih besar.",
          reviewFocus: "Compare the first place that differs.",
          reviewFocusBm: "Bandingkan tempat pertama yang berbeza.",
        },
        "2": {
          misconceptionCode: "place_ignored",
          hint: "The numbers are not equal: the ten-thousands digits are 9 and 0.",
          hintBm: "Nombor tidak sama: digit puluh ribu ialah 9 dan 0.",
          example: "In 5 820 000 and 5 280 000, the ten-thousands differ.",
          exampleBm: "Dalam 5 820 000 dan 5 280 000, puluh ribu berbeza.",
          reviewFocus: "Compare digit by digit from the left.",
          reviewFocusBm: "Bandingkan digit demi digit dari kiri.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "Both numbers have seven digits, so compare the digits themselves.",
          hintBm: "Kedua-dua nombor mempunyai tujuh digit, jadi bandingkan digit itu sendiri.",
          example: "In 9 000 100 and 9 100 000, both have seven digits.",
          exampleBm: "Dalam 9 000 100 dan 9 100 000, kedua-duanya mempunyai tujuh digit.",
          reviewFocus: "Compare place values, not just digit counts.",
          reviewFocusBm: "Bandingkan nilai tempat, bukan hanya bilangan digit.",
        },
      },
    },
  ),
];

const difficulties = ["Easy", "Moderate", "Hard"];
const questionBanks = Object.fromEntries(
  difficulties.map((difficulty) => {
    const bankId = bankIdFor(difficulty);
    return [
      bankId,
      {
        bankId,
        topicId,
        subtopicId,
        skillId,
        yearLevel: 6,
        difficultyLevel: difficulty,
        questionIds: questions
          .filter((item) => item.bankId === bankId)
          .map((item) => item.id),
        version: CONTENT_VERSION,
        isActive: true,
        sourceMaterialId: enMaterialId,
        sourceMaterialIdBm: bmMaterialId,
      },
    ];
  }),
);

function validateQuestionBankSeed() {
  if (Object.keys(questionBanks).length !== 3) {
    throw new Error("Expected exactly three Year 6 read/write banks.");
  }
  const ids = new Set();
  for (const [bankId, bank] of Object.entries(questionBanks)) {
    if (bank.questionIds.length !== 5) {
      throw new Error(`Invalid bank ${bankId}: expected exactly five questions.`);
    }
    for (const id of bank.questionIds) {
      if (ids.has(id)) throw new Error(`Question ${id} appears more than once.`);
      ids.add(id);
    }
  }
}

module.exports = { questionBanks, questions, validateQuestionBankSeed };
