// Year 5 Whole Numbers - Recognise and Write Numbers (1.1.1).
// Source-grounded in MATHEMATICS Y5 - 1 OF 2.pdf (pp. 7-10) and
// MATEMATIK T5 SK - 1 DRP 2.pdf: numbers up to 1 000 000.
const {
  CONTENT_VERSION,
  AUTHOR_ID,
  REVIEWER_ID,
  APPROVED_AT,
} = require("./content_source_manifest");

const topicId = "whole_numbers_y5";
const subtopicId = "read_write_numbers";
const skillId = "y5_whole_numbers_read_write";
const createdAt = "2026-08-12T00:00:00Z";
const enMaterialId = "en_y5_1";
const bmMaterialId = "bm_y5_1";
const enBook = "MATHEMATICS Y5 - 1 OF 2";
const bmBook = "MATEMATIK T5 SK - 1 DRP 2";
const standardCode =
  "1.1.1 Recognise and Write Numbers / Kenal dan Tulis Nombor";
const sectionClass = "exercise";

const bankIdFor = (difficulty) =>
  `y5_whole_read_write_${difficulty.toLowerCase()}_v1`;

function question(
  suffix,
  difficulty,
  estimatedDifficulty,
  questionText,
  questionTextBm,
  options,
  optionsBm,
  answerIndex,
  meta,
) {
  const questionId = `q_y5_whole_read_write_${suffix}`;
  const order = Number(suffix.slice(-2)) - 1;
  return {
    id: questionId,
    bankId: bankIdFor(difficulty),
    client: {
      questionId,
      bankId: bankIdFor(difficulty),
      topicId,
      subtopicId,
      skillId,
      yearLevel: 5,
      difficultyLevel: difficulty,
      estimatedDifficulty,
      contentVersion: CONTENT_VERSION,
      language: "bilingual",
      createdAt,
      order,
      questionText,
      questionTextBm,
      options,
      optionsBm,
      questionType: meta.questionType,
      questionTypeBm: meta.questionTypeBm,
      sourceMaterialId: enMaterialId,
      sourceMaterialIdBm: bmMaterialId,
      sourceLocator: meta.sourceLocator,
      sourceLocatorBm: meta.sourceLocatorBm,
      sourceSectionClass: meta.sourceSectionClass ?? sectionClass,
      sectionJustification: meta.sectionJustification ?? "",
      isActive: true,
    },
    answerKey: {
      questionId,
      answerIndex,
      feedbackByOption: meta.feedbackByOption,
      difficultyReview: meta.difficultyReview,
      contentVersion: CONTENT_VERSION,
      createdAt,
      isActive: true,
      sourceMaterialId: enMaterialId,
      sourceMaterialIdBm: bmMaterialId,
      authorId: AUTHOR_ID,
      reviewerId: REVIEWER_ID,
      approvedAt: APPROVED_AT,
    },
  };
}

const questions = [
  question(
    "easy_01",
    "Easy",
    0.15,
    "Which numeral shows six hundred two thousand three hundred and thirty-seven?",
    "Angka manakah menunjukkan enam ratus dua ribu tiga ratus tiga puluh tujuh?",
    ["602 337", "620 337", "602 373", "623 037"],
    ["602 337", "620 337", "602 373", "623 037"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 7`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 7`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "ten_thousands_swapped",
          hint: "The number begins with six hundred and two thousand, so the second group is 02, not 20.",
          hintBm: "Nombor bermula dengan enam ratus dua ribu, jadi kumpulan kedua ialah 02, bukan 20.",
          example: "In 803 000, the thousands group is 803.",
          exampleBm: "Dalam 803 000, kumpulan ribu ialah 803.",
          reviewFocus: "Write the thousands group in the same order as the words.",
          reviewFocusBm: "Tulis kumpulan ribu dalam tertib yang sama seperti perkataan.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is thirty-seven: 3 tens and 7 ones. Keep the tens before the ones.",
          hintBm: "Hujungnya ialah tiga puluh tujuh: 3 puluh dan 7 sa. Kekalkan puluh sebelum sa.",
          example: "In 514 293, the ending 293 is two hundred ninety-three.",
          exampleBm: "Dalam 514 293, hujung 293 ialah dua ratus sembilan puluh tiga.",
          reviewFocus: "Read the last three digits as a group.",
          reviewFocusBm: "Baca tiga digit terakhir sebagai satu kumpulan.",
        },
        "3": {
          misconceptionCode: "digit_group_swap",
          hint: "The thousands group is six hundred and two, not six hundred and twenty-three.",
          hintBm: "Kumpulan ribu ialah enam ratus dua, bukan enam ratus dua puluh tiga.",
          example: "In 741 000, the thousands group is 741.",
          exampleBm: "Dalam 741 000, kumpulan ribu ialah 741.",
          reviewFocus: "Keep the groups separate when writing the numeral.",
          reviewFocusBm: "Kekalkan kumpulan berasingan apabila menulis angka.",
        },
      },
    },
  ),
  question(
    "easy_02",
    "Easy",
    0.15,
    "Which number is written as 522 034?",
    "Nombor manakah ditulis sebagai 522 034?",
    [
      "five hundred twenty-two thousand and thirty-four",
      "five hundred twenty-two thousand three hundred and four",
      "five hundred two thousand and thirty-four",
      "fifty-two thousand and thirty-four",
    ],
    [
      "lima ratus dua puluh dua ribu tiga puluh empat",
      "lima ratus dua puluh dua ribu tiga ratus empat",
      "lima ratus dua ribu tiga puluh empat",
      "lima puluh dua ribu tiga puluh empat",
    ],
    0,
    {
      questionType: "Read a numeral in words",
      questionTypeBm: "Baca angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 7`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 7`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "hundreds_place_added",
          hint: "The last three digits are 034: there is a zero hundreds, so the ending is thirty-four, not three hundred and four.",
          hintBm: "Tiga digit terakhir ialah 034: terdapat sifar ratus, jadi hujungnya ialah tiga puluh empat, bukan tiga ratus empat.",
          example: "In 617 042, the ending 042 is forty-two.",
          exampleBm: "Dalam 617 042, hujung 042 ialah empat puluh dua.",
          reviewFocus: "Check the zero hundreds digit before reading the ending.",
          reviewFocusBm: "Semak digit ratus sifar sebelum membaca hujung.",
        },
        "2": {
          misconceptionCode: "zero_thousands_dropped",
          hint: "There are five hundred and twenty-two thousands. The zero in the thousands group does not remove the twenty.",
          hintBm: "Terdapat lima ratus dua puluh dua ribu. Sifar dalam kumpulan ribu tidak menghilangkan dua puluh.",
          example: "In 706 015, the thousands group is 706.",
          exampleBm: "Dalam 706 015, kumpulan ribu ialah 706.",
          reviewFocus: "Read the full thousands group before the last three digits.",
          reviewFocusBm: "Baca kumpulan ribu penuh sebelum tiga digit terakhir.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "522 034 has six digits. Count the places before choosing the words.",
          hintBm: "522 034 mempunyai enam digit. Kira tempat sebelum memilih perkataan.",
          example: "In 908 123, there are six digits.",
          exampleBm: "Dalam 908 123, terdapat enam digit.",
          reviewFocus: "Match the number of digits with the words.",
          reviewFocusBm: "Padankan bilangan digit dengan perkataan.",
        },
      },
    },
  ),
  question(
    "easy_03",
    "Easy",
    0.18,
    "Write two hundred thousand and fifteen in numerals.",
    "Tulis dua ratus ribu lima belas dalam angka.",
    ["200 015", "200 150", "20 015", "2 000 015"],
    ["200 015", "200 150", "20 015", "2 000 015"],
    0,
    {
      questionType: "Write a number in words as numerals",
      questionTypeBm: "Tulis nombor dalam perkataan sebagai angka",
      sourceLocator: `${enBook}, ${standardCode}, p. 8`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 8`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_swapped",
          hint: "Fifteen is 1 ten and 5 ones, so the ending is 015, not 150.",
          hintBm: "Lima belas ialah 1 puluh dan 5 sa, jadi hujungnya ialah 015, bukan 150.",
          example: "In 340 018, the ending 018 is eighteen.",
          exampleBm: "Dalam 340 018, hujung 018 ialah lapan belas.",
          reviewFocus: "Place fifteen in the tens and ones places.",
          reviewFocusBm: "Letakkan lima belas di tempat puluh dan sa.",
        },
        "2": {
          misconceptionCode: "zero_thousands_dropped",
          hint: "Two hundred thousand needs six digits: 200, then three more digits.",
          hintBm: "Dua ratus ribu memerlukan enam digit: 200, kemudian tiga digit lagi.",
          example: "In 400 000, there are six digits.",
          exampleBm: "Dalam 400 000, terdapat enam digit.",
          reviewFocus: "Keep the two zeros in the thousands group.",
          reviewFocusBm: "Kekalkan dua sifar dalam kumpulan ribu.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "Two hundred thousand is not two million. The number has six digits, not seven.",
          hintBm: "Dua ratus ribu bukan dua juta. Nombor ini mempunyai enam digit, bukan tujuh.",
          example: "In 900 000, there are six digits.",
          exampleBm: "Dalam 900 000, terdapat enam digit.",
          reviewFocus: "Check the digit count matches the words.",
          reviewFocusBm: "Semak bilangan digit sepadan dengan perkataan.",
        },
      },
    },
  ),
  question(
    "easy_04",
    "Easy",
    0.18,
    "Which numeral matches one hundred twenty-five thousand and seventy?",
    "Angka manakah sepadan dengan seratus dua puluh lima ribu tujuh puluh?",
    ["125 070", "125 700", "125 007", "152 070"],
    ["125 070", "125 700", "125 007", "152 070"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 8`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 8`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_place_shifted",
          hint: "Seventy belongs in the tens place, so the ones digit stays zero and the hundreds digit is zero.",
          hintBm: "Tujuh puluh berada di tempat puluh, jadi digit sa kekal sifar dan digit ratus ialah sifar.",
          example: "In 230 050, the ending 050 is fifty.",
          exampleBm: "Dalam 230 050, hujung 050 ialah lima puluh.",
          reviewFocus: "Write seventy with the tens digit and zeros around it.",
          reviewFocusBm: "Tulis tujuh puluh dengan digit puluh dan sifar di sekelilingnya.",
        },
        "2": {
          misconceptionCode: "tens_ones_misread",
          hint: "The word is seventy, not seven. The 7 is in the tens place.",
          hintBm: "Perkataan ialah tujuh puluh, bukan tujuh. Digit 7 berada di tempat puluh.",
          example: "In 415 080, the ending 080 is eighty.",
          exampleBm: "Dalam 415 080, hujung 080 ialah lapan puluh.",
          reviewFocus: "Place the tens value correctly.",
          reviewFocusBm: "Letakkan nilai puluh dengan betul.",
        },
        "3": {
          misconceptionCode: "digit_group_swap",
          hint: "The thousands group is one hundred and twenty-five, so it starts with 125, not 152.",
          hintBm: "Kumpulan ribu ialah seratus dua puluh lima, jadi ia bermula dengan 125, bukan 152.",
          example: "In 261 000, the thousands group is 261.",
          exampleBm: "Dalam 261 000, kumpulan ribu ialah 261.",
          reviewFocus: "Keep the thousands group in order.",
          reviewFocusBm: "Kekalkan kumpulan ribu mengikut tertib.",
        },
      },
    },
  ),
  question(
    "easy_05",
    "Easy",
    0.2,
    "Which words match 900 017?",
    "Perkataan manakah sepadan dengan 900 017?",
    [
      "nine hundred thousand and seventeen",
      "ninety thousand and seventeen",
      "nine hundred thousand and seventy",
      "nine hundred seventeen thousand",
    ],
    [
      "sembilan ratus ribu tujuh belas",
      "sembilan puluh ribu tujuh belas",
      "sembilan ratus ribu tujuh puluh",
      "sembilan ratus tujuh belas ribu",
    ],
    0,
    {
      questionType: "Write a numeral in words",
      questionTypeBm: "Tulis angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "direct_recall",
        reasoningStepCount: 1,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_thousands_dropped",
          hint: "There are nine hundred thousands, so the number starts with nine hundred thousand, not ninety thousand.",
          hintBm: "Terdapat sembilan ratus ribu, jadi nombor bermula dengan sembilan ratus ribu, bukan sembilan puluh ribu.",
          example: "In 600 012, the thousands group is 600.",
          exampleBm: "Dalam 600 012, kumpulan ribu ialah 600.",
          reviewFocus: "Read the hundreds-thousands digit as a hundred value.",
          reviewFocusBm: "Baca digit ratus ribu sebagai nilai ratus.",
        },
        "2": {
          misconceptionCode: "tens_ones_misread",
          hint: "The ending is 017: seventeen, not seventy.",
          hintBm: "Hujungnya ialah 017: tujuh belas, bukan tujuh puluh.",
          example: "In 800 019, the ending 019 is nineteen.",
          exampleBm: "Dalam 800 019, hujung 019 ialah sembilan belas.",
          reviewFocus: "Check the last two digits are in the right order.",
          reviewFocusBm: "Semak dua digit terakhir mengikut tertib yang betul.",
        },
        "3": {
          misconceptionCode: "group_value_mixed",
          hint: "The 17 is in the ones group, not the thousands group. Keep the groups separate.",
          hintBm: "Angka 17 berada dalam kumpulan sa, bukan kumpulan ribu. Kekalkan kumpulan berasingan.",
          example: "In 450 006, the 6 is in the ones group.",
          exampleBm: "Dalam 450 006, digit 6 berada dalam kumpulan sa.",
          reviewFocus: "Name the thousands group, then the last three digits.",
          reviewFocusBm: "Sebut kumpulan ribu, kemudian tiga digit terakhir.",
        },
      },
    },
  ),
  question(
    "moderate_01",
    "Moderate",
    0.45,
    "A card says 630 205. Which sentence reads it correctly?",
    "Kad menunjukkan 630 205. Ayat manakah membacanya dengan betul?",
    [
      "six hundred thirty thousand two hundred and five",
      "six hundred three thousand two hundred and five",
      "six hundred thirty thousand two hundred fifty",
      "sixty-three thousand two hundred and five",
    ],
    [
      "enam ratus tiga puluh ribu dua ratus lima",
      "enam ratus tiga ribu dua ratus lima",
      "enam ratus tiga puluh ribu dua ratus lima puluh",
      "enam puluh tiga ribu dua ratus lima",
    ],
    0,
    {
      questionType: "Read a numeral in words",
      questionTypeBm: "Baca angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 630: six hundred and thirty, not six hundred and three. The zero keeps the thirty in place.",
          hintBm: "Kumpulan ribu ialah 630: enam ratus tiga puluh, bukan enam ratus tiga. Sifar mengekalkan tiga puluh pada tempatnya.",
          example: "In 240 018, the thousands group is 240.",
          exampleBm: "Dalam 240 018, kumpulan ribu ialah 240.",
          reviewFocus: "Read the whole thousands group.",
          reviewFocusBm: "Baca keseluruhan kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "tens_ones_misread",
          hint: "The ending is 205: two hundred and five, not two hundred and fifty.",
          hintBm: "Hujungnya ialah 205: dua ratus lima, bukan dua ratus lima puluh.",
          example: "In 310 407, the ending 407 is four hundred and seven.",
          exampleBm: "Dalam 310 407, hujung 407 ialah empat ratus tujuh.",
          reviewFocus: "Read the last three digits together.",
          reviewFocusBm: "Baca tiga digit terakhir bersama-sama.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "630 205 has six digits. Sixty-three thousand has only five digits.",
          hintBm: "630 205 mempunyai enam digit. Enam puluh tiga ribu hanya mempunyai lima digit.",
          example: "In 900 123, there are six digits.",
          exampleBm: "Dalam 900 123, terdapat enam digit.",
          reviewFocus: "Count the digits before reading.",
          reviewFocusBm: "Kira digit sebelum membaca.",
        },
      },
    },
  ),
  question(
    "moderate_02",
    "Moderate",
    0.45,
    "Which numeral represents seven hundred thousand five hundred and forty-eight?",
    "Angka manakah mewakili tujuh ratus ribu lima ratus empat puluh lapan?",
    ["700 548", "705 048", "700 458", "70 548"],
    ["700 548", "705 048", "700 458", "70 548"],
    0,
    {
      questionType: "Choose a numeral for a number in words",
      questionTypeBm: "Pilih angka bagi nombor dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "hundreds_place_shifted",
          hint: "Five hundred and forty-eight is the last group: 548. The ten-thousands digit stays zero.",
          hintBm: "Lima ratus empat puluh lapan ialah kumpulan terakhir: 548. Digit puluh ribu kekal sifar.",
          example: "In 600 219, the last group is 219.",
          exampleBm: "Dalam 600 219, kumpulan terakhir ialah 219.",
          reviewFocus: "Write the hundreds, tens, and ones in one group.",
          reviewFocusBm: "Tulis ratus, puluh dan sa dalam satu kumpulan.",
        },
        "2": {
          misconceptionCode: "digit_order_swapped",
          hint: "The order is five hundred, then forty-eight: 548, not 458.",
          hintBm: "Tertibnya ialah lima ratus, kemudian empat puluh lapan: 548, bukan 458.",
          example: "In 320 645, the last group is 645.",
          exampleBm: "Dalam 320 645, kumpulan terakhir ialah 645.",
          reviewFocus: "Keep the hundreds before the tens.",
          reviewFocusBm: "Kekalkan ratus sebelum puluh.",
        },
        "3": {
          misconceptionCode: "zero_thousands_dropped",
          hint: "Seven hundred thousand needs six digits. The thousands and ten-thousands places are both zero.",
          hintBm: "Tujuh ratus ribu memerlukan enam digit. Tempat ribu dan puluh ribu kedua-duanya sifar.",
          example: "In 800 000, there are six digits.",
          exampleBm: "Dalam 800 000, terdapat enam digit.",
          reviewFocus: "Check the number has six digits.",
          reviewFocusBm: "Semak nombor mempunyai enam digit.",
        },
      },
    },
  ),
  question(
    "moderate_03",
    "Moderate",
    0.48,
    "Which words match 820 029?",
    "Perkataan manakah sepadan dengan 820 029?",
    [
      "eight hundred twenty thousand and twenty-nine",
      "eight hundred two thousand and twenty-nine",
      "eight hundred twenty thousand two hundred and nine",
      "eighty-two thousand and twenty-nine",
    ],
    [
      "lapan ratus dua puluh ribu dua puluh sembilan",
      "lapan ratus dua ribu dua puluh sembilan",
      "lapan ratus dua puluh ribu dua ratus sembilan",
      "lapan puluh dua ribu dua puluh sembilan",
    ],
    0,
    {
      questionType: "Write a numeral in words",
      questionTypeBm: "Tulis angka dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 820: eight hundred and twenty, not eight hundred and two.",
          hintBm: "Kumpulan ribu ialah 820: lapan ratus dua puluh, bukan lapan ratus dua.",
          example: "In 530 004, the thousands group is 530.",
          exampleBm: "Dalam 530 004, kumpulan ribu ialah 530.",
          reviewFocus: "Read the whole thousands group.",
          reviewFocusBm: "Baca keseluruhan kumpulan ribu.",
        },
        "2": {
          misconceptionCode: "hundreds_place_added",
          hint: "The ending is 029: twenty-nine, with a zero hundreds digit.",
          hintBm: "Hujungnya ialah 029: dua puluh sembilan, dengan digit ratus sifar.",
          example: "In 410 038, the ending 038 is thirty-eight.",
          exampleBm: "Dalam 410 038, hujung 038 ialah tiga puluh lapan.",
          reviewFocus: "Check the hundreds digit of the ending.",
          reviewFocusBm: "Semak digit ratus pada hujung.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "820 029 has six digits, so the words must name six-digit values.",
          hintBm: "820 029 mempunyai enam digit, jadi perkataan mesti menyebut nilai enam digit.",
          example: "In 700 015, there are six digits.",
          exampleBm: "Dalam 700 015, terdapat enam digit.",
          reviewFocus: "Count the digits and match the groups.",
          reviewFocusBm: "Kira digit dan padankan kumpulan.",
        },
      },
    },
  ),
  question(
    "moderate_04",
    "Moderate",
    0.48,
    "Write five hundred eighty thousand and seven in numerals.",
    "Tulis lima ratus lapan puluh ribu tujuh dalam angka.",
    ["580 007", "580 070", "508 007", "580 700"],
    ["580 007", "580 070", "508 007", "580 700"],
    0,
    {
      questionType: "Write a number in words as numerals",
      questionTypeBm: "Tulis nombor dalam perkataan sebagai angka",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "tens_ones_misread",
          hint: "The word is seven, not seventy. The 7 belongs in the ones place.",
          hintBm: "Perkataan ialah tujuh, bukan tujuh puluh. Digit 7 berada di tempat sa.",
          example: "In 260 003, the ending 003 is three.",
          exampleBm: "Dalam 260 003, hujung 003 ialah tiga.",
          reviewFocus: "Place the ones digit at the end.",
          reviewFocusBm: "Letakkan digit sa di hujung.",
        },
        "2": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The thousands group is 580: five hundred and eighty, not five hundred and eight.",
          hintBm: "Kumpulan ribu ialah 580: lima ratus lapan puluh, bukan lima ratus lapan.",
          example: "In 340 000, the thousands group is 340.",
          exampleBm: "Dalam 340 000, kumpulan ribu ialah 340.",
          reviewFocus: "Keep the zero in the ten-thousands place.",
          reviewFocusBm: "Kekalkan sifar di tempat puluh ribu.",
        },
        "3": {
          misconceptionCode: "hundreds_tens_shifted",
          hint: "The hundreds and tens of the thousands group are 5 and 8. The 7 is a ones value, not hundreds.",
          hintBm: "Ratus dan puluh dalam kumpulan ribu ialah 5 dan 8. Digit 7 ialah nilai sa, bukan ratus.",
          example: "In 900 002, the 2 is in the ones place.",
          exampleBm: "Dalam 900 002, digit 2 berada di tempat sa.",
          reviewFocus: "Write each digit in its place.",
          reviewFocusBm: "Tulis setiap digit pada tempatnya.",
        },
      },
    },
  ),
  question(
    "moderate_05",
    "Moderate",
    0.5,
    "Which number has 7 hundred-thousands, 8 ten-thousands, 1 thousand, 4 hundreds, 3 tens, and 6 ones?",
    "Nombor manakah mempunyai 7 ratus ribu, 8 puluh ribu, 1 ribu, 4 ratus, 3 puluh dan 6 sa?",
    ["781 436", "781 346", "718 436", "781 463"],
    ["781 436", "781 346", "718 436", "781 463"],
    0,
    {
      questionType: "Build a number from place values",
      questionTypeBm: "Bina nombor daripada nilai tempat",
      sourceLocator: `${enBook}, 1.1.2 Place Value, p. 10`,
      sourceLocatorBm: `${bmBook}, 1.1.2 Nilai Tempat, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "linked_step",
        reasoningStepCount: 2,
        transferRequired: false,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "place_order_swapped",
          hint: "The hundreds digit is 4 and the tens digit is 3. Write hundreds before tens.",
          hintBm: "Digit ratus ialah 4 dan digit puluh ialah 3. Tulis ratus sebelum puluh.",
          example: "In 532, the hundreds digit is 5.",
          exampleBm: "Dalam 532, digit ratus ialah 5.",
          reviewFocus: "Order the digits from the largest place.",
          reviewFocusBm: "Susun digit daripada tempat terbesar.",
        },
        "2": {
          misconceptionCode: "group_value_mixed",
          hint: "The first digit is 7 hundred-thousands, so the number starts with 7, then 8 ten-thousands and 1 thousand.",
          hintBm: "Digit pertama ialah 7 ratus ribu, jadi nombor bermula dengan 7, kemudian 8 puluh ribu dan 1 ribu.",
          example: "In 613, the first digit is the hundreds digit.",
          exampleBm: "Dalam 613, digit pertama ialah digit ratus.",
          reviewFocus: "Build the thousands group first.",
          reviewFocusBm: "Bina kumpulan ribu dahulu.",
        },
        "3": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The tens digit is 3 and the ones digit is 6, so the ending is 36.",
          hintBm: "Digit puluh ialah 3 dan digit sa ialah 6, jadi hujungnya ialah 36.",
          example: "In 921, the ending is twenty-one.",
          exampleBm: "Dalam 921, hujungnya ialah dua puluh satu.",
          reviewFocus: "Check the last two digits are in order.",
          reviewFocusBm: "Semak dua digit terakhir mengikut tertib.",
        },
      },
    },
  ),
  question(
    "hard_01",
    "Hard",
    0.75,
    "Which pair of numbers and words does not match?",
    "Pasangan nombor dan perkataan manakah tidak sepadan?",
    [
      "528 314 - five hundred twenty-eight thousand three hundred and fourteen",
      "409 032 - four hundred nine thousand and thirty-two",
      "603 804 - six hundred three thousand eight hundred and four",
      "770 835 - seven hundred seven thousand eight hundred and thirty-five",
    ],
    [
      "528 314 - lima ratus dua puluh lapan ribu tiga ratus empat belas",
      "409 032 - empat ratus sembilan ribu tiga puluh dua",
      "603 804 - enam ratus tiga ribu lapan ratus empat",
      "770 835 - tujuh ratus tujuh ribu lapan ratus tiga puluh lima",
    ],
    3,
    {
      questionType: "Check number-word pairs",
      questionTypeBm: "Semak pasangan nombor-perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "0": {
          misconceptionCode: "pair_misread",
          hint: "528 314 has five hundred and twenty-eight thousands. Check that every pair reads the same groups.",
          hintBm: "528 314 mempunyai lima ratus dua puluh lapan ribu. Semak setiap pasangan membaca kumpulan yang sama.",
          example: "In 641 207, the groups are 641 and 207.",
          exampleBm: "Dalam 641 207, kumpulannya ialah 641 dan 207.",
          reviewFocus: "Compare the thousands group in each pair.",
          reviewFocusBm: "Bandingkan kumpulan ribu dalam setiap pasangan.",
        },
        "1": {
          misconceptionCode: "pair_misread",
          hint: "409 032 has a zero thousands digit. The words four hundred and nine thousand keep that zero.",
          hintBm: "409 032 mempunyai digit ribu sifar. Perkataan empat ratus sembilan ribu mengekalkan sifar itu.",
          example: "In 205 017, the groups are 205 and 017.",
          exampleBm: "Dalam 205 017, kumpulannya ialah 205 dan 017.",
          reviewFocus: "Check the zero digits are read correctly.",
          reviewFocusBm: "Semak digit sifar dibaca dengan betul.",
        },
        "2": {
          misconceptionCode: "pair_misread",
          hint: "603 804 has six hundred and three thousands. The ending 804 is eight hundred and four.",
          hintBm: "603 804 mempunyai enam ratus tiga ribu. Hujung 804 ialah lapan ratus empat.",
          example: "In 507 312, the groups are 507 and 312.",
          exampleBm: "Dalam 507 312, kumpulannya ialah 507 dan 312.",
          reviewFocus: "Read each group of three digits separately.",
          reviewFocusBm: "Baca setiap kumpulan tiga digit secara berasingan.",
        },
      },
    },
  ),
  question(
    "hard_02",
    "Hard",
    0.75,
    "Which number has the same wording pattern as 200 015?",
    "Nombor manakah mempunyai pola bacaan yang sama seperti 200 015?",
    ["300 026", "300 260", "326 000", "30 026"],
    ["300 026", "300 260", "326 000", "30 026"],
    0,
    {
      questionType: "Compare wording patterns",
      questionTypeBm: "Bandingkan pola bacaan",
      sourceLocator: `${enBook}, ${standardCode}, p. 8`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 8`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_place_shift",
          hint: "200 015 ends with fifteen in the tens and ones. The hundreds digit of the ending must stay zero.",
          hintBm: "200 015 berakhir dengan lima belas pada puluh dan sa. Digit ratus pada hujung mesti kekal sifar.",
          example: "In 400 017, the ending is seventeen.",
          exampleBm: "Dalam 400 017, hujungnya ialah tujuh belas.",
          reviewFocus: "Compare the last three digits.",
          reviewFocusBm: "Bandingkan tiga digit terakhir.",
        },
        "2": {
          misconceptionCode: "group_value_mixed",
          hint: "200 015 has a zero hundreds digit and zero ten-thousands digit? No - it has 2 hundred-thousands. Find a number with the same zero pattern in the last three digits.",
          hintBm: "200 015 mempunyai digit ratus sifar dan digit puluh ribu sifar? Tidak - ia mempunyai 2 ratus ribu. Cari nombor dengan pola sifar yang sama dalam tiga digit terakhir.",
          example: "In 500 009, the last three digits are 009.",
          exampleBm: "Dalam 500 009, tiga digit terakhir ialah 009.",
          reviewFocus: "Match the thousands group size and the zero pattern.",
          reviewFocusBm: "Padankan saiz kumpulan ribu dan pola sifar.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "200 015 has six digits. Count the digits of each option before comparing.",
          hintBm: "200 015 mempunyai enam digit. Kira digit setiap pilihan sebelum membandingkan.",
          example: "In 300 004, there are six digits.",
          exampleBm: "Dalam 300 004, terdapat enam digit.",
          reviewFocus: "Check the number of digits first.",
          reviewFocusBm: "Semak bilangan digit dahulu.",
        },
      },
    },
  ),
  question(
    "hard_03",
    "Hard",
    0.78,
    "A pupil writes 700 548 as seven hundred five thousand and forty-eight. What is the best correction?",
    "Murid menulis 700 548 sebagai tujuh ratus lima ribu empat puluh lapan. Apakah pembetulan terbaik?",
    [
      "It should be seven hundred thousand five hundred and forty-eight.",
      "It should be seven hundred five thousand four hundred and eight.",
      "It should be seventy thousand five hundred and forty-eight.",
      "It should be seven hundred thousand five hundred and eighty-four.",
    ],
    [
      "Sepatutnya tujuh ratus ribu lima ratus empat puluh lapan.",
      "Sepatutnya tujuh ratus lima ribu empat ratus lapan.",
      "Sepatutnya tujuh puluh ribu lima ratus empat puluh lapan.",
      "Sepatutnya tujuh ratus ribu lima ratus lapan puluh empat.",
    ],
    0,
    {
      questionType: "Correct a number written in words",
      questionTypeBm: "Betulkan nombor yang ditulis dalam perkataan",
      sourceLocator: `${enBook}, ${standardCode}, p. 9`,
      sourceLocatorBm: `${bmBook}, ${standardCode}, hlm. 9`,
      difficultyReview: {
        cognitiveDemand: "multi_step",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_dropped",
          hint: "The 5 is in the hundreds place, not the ten-thousands place. Keep the zero in the ten-thousands place.",
          hintBm: "Digit 5 berada di tempat ratus, bukan di tempat puluh ribu. Kekalkan sifar di tempat puluh ribu.",
          example: "In 800 340, the 3 is in the hundreds place.",
          exampleBm: "Dalam 800 340, digit 3 berada di tempat ratus.",
          reviewFocus: "Name each digit by its place.",
          reviewFocusBm: "Sebut setiap digit mengikut tempatnya.",
        },
        "2": {
          misconceptionCode: "hundred_thousands_misread",
          hint: "The 7 is in the hundred-thousands place, so the words begin with seven hundred thousand.",
          hintBm: "Digit 7 berada di tempat ratus ribu, jadi perkataan bermula dengan tujuh ratus ribu.",
          example: "In 900 020, the 9 is in the hundred-thousands place.",
          exampleBm: "Dalam 900 020, digit 9 berada di tempat ratus ribu.",
          reviewFocus: "Check the first digit's place.",
          reviewFocusBm: "Semak tempat digit pertama.",
        },
        "3": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The ending is 548: five hundred and forty-eight, not five hundred and eighty-four.",
          hintBm: "Hujungnya ialah 548: lima ratus empat puluh lapan, bukan lima ratus lapan puluh empat.",
          example: "In 620 347, the ending 347 is three hundred and forty-seven.",
          exampleBm: "Dalam 620 347, hujung 347 ialah tiga ratus empat puluh tujuh.",
          reviewFocus: "Read the last three digits in order.",
          reviewFocusBm: "Baca tiga digit terakhir mengikut tertib.",
        },
      },
    },
  ),
  question(
    "hard_04",
    "Hard",
    0.78,
    "Which number fits: 9 hundred-thousands, 0 ten-thousands, 3 thousands, 6 hundreds, 7 tens, 1 one?",
    "Nombor manakah sepadan: 9 ratus ribu, 0 puluh ribu, 3 ribu, 6 ratus, 7 puluh, 1 sa?",
    ["903 671", "930 671", "903 617", "93 671"],
    ["903 671", "930 671", "903 617", "93 671"],
    0,
    {
      questionType: "Build a number from place values",
      questionTypeBm: "Bina nombor daripada nilai tempat",
      sourceLocator: `${enBook}, 1.1.2 Place Value, p. 10`,
      sourceLocatorBm: `${bmBook}, 1.1.2 Nilai Tempat, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "multi_step",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "zero_ten_thousands_skipped",
          hint: "There are zero ten-thousands, so the second digit must be 0, not 3.",
          hintBm: "Terdapat sifar puluh ribu, jadi digit kedua mesti 0, bukan 3.",
          example: "In 6 0 2 9, the digits follow the places in order.",
          exampleBm: "Dalam 6 0 2 9, digit mengikut tempat mengikut tertib.",
          reviewFocus: "Keep the zero ten-thousands place.",
          reviewFocusBm: "Kekalkan tempat puluh ribu sifar.",
        },
        "2": {
          misconceptionCode: "tens_ones_swapped",
          hint: "The tens digit is 7 and the ones digit is 1, so the ending is 71.",
          hintBm: "Digit puluh ialah 7 dan digit sa ialah 1, jadi hujungnya ialah 71.",
          example: "In 542, the tens digit is 4 and the ones digit is 2.",
          exampleBm: "Dalam 542, digit puluh ialah 4 dan digit sa ialah 2.",
          reviewFocus: "Write tens before ones.",
          reviewFocusBm: "Tulis puluh sebelum sa.",
        },
        "3": {
          misconceptionCode: "digit_count_misread",
          hint: "Nine hundred-thousands needs six digits. Count the digits in each option.",
          hintBm: "Sembilan ratus ribu memerlukan enam digit. Kira digit dalam setiap pilihan.",
          example: "In 800 000, there are six digits.",
          exampleBm: "Dalam 800 000, terdapat enam digit.",
          reviewFocus: "Check the digit count before comparing.",
          reviewFocusBm: "Semak bilangan digit sebelum membandingkan.",
        },
      },
    },
  ),
  question(
    "hard_05",
    "Hard",
    0.8,
    "Which statement correctly compares 409 032 and 409 320?",
    "Pernyataan manakah membandingkan 409 032 dan 409 320 dengan betul?",
    [
      "409 320 is greater because it has 3 hundreds.",
      "409 032 is greater because it has 3 tens.",
      "They are equal.",
      "409 320 has 4 hundred-thousands.",
    ],
    [
      "409 320 lebih besar kerana mempunyai 3 ratus.",
      "409 032 lebih besar kerana mempunyai 3 puluh.",
      "Kedua-duanya sama.",
      "409 320 mempunyai 4 ratus ribu.",
    ],
    0,
    {
      questionType: "Compare two numbers",
      questionTypeBm: "Bandingkan dua nombor",
      sourceLocator: `${enBook}, 1.1.2 Place Value, p. 10`,
      sourceLocatorBm: `${bmBook}, 1.1.2 Nilai Tempat, hlm. 10`,
      difficultyReview: {
        cognitiveDemand: "transfer",
        reasoningStepCount: 3,
        transferRequired: true,
      },
      feedbackByOption: {
        "1": {
          misconceptionCode: "ones_vs_hundreds_value",
          hint: "A digit in the hundreds place is worth more than a digit in the tens place.",
          hintBm: "Digit di tempat ratus bernilai lebih daripada digit di tempat puluh.",
          example: "Between 305 and 350, 350 is greater because of the hundreds place? No - compare 0 tens with 5 tens.",
          exampleBm: "Antara 305 dan 350, 350 lebih besar kerana 0 puluh berbanding 5 puluh.",
          reviewFocus: "Compare the first place that differs.",
          reviewFocusBm: "Bandingkan tempat pertama yang berbeza.",
        },
        "2": {
          misconceptionCode: "place_ignored",
          hint: "The numbers are not equal: 409 032 ends with 032 and 409 320 ends with 320.",
          hintBm: "Nombor tidak sama: 409 032 berakhir dengan 032 dan 409 320 berakhir dengan 320.",
          example: "In 502 017 and 502 107, the hundreds differ.",
          exampleBm: "Dalam 502 017 dan 502 107, ratus berbeza.",
          reviewFocus: "Compare digit by digit from the left.",
          reviewFocusBm: "Bandingkan digit demi digit dari kiri.",
        },
        "3": {
          misconceptionCode: "group_value_mixed",
          hint: "Both numbers have 4 hundred-thousands. Compare the places after that.",
          hintBm: "Kedua-dua nombor mempunyai 4 ratus ribu. Bandingkan tempat selepas itu.",
          example: "In 813 000 and 814 000, the thousands digits differ.",
          exampleBm: "Dalam 813 000 dan 814 000, digit ribu berbeza.",
          reviewFocus: "Compare the ten-thousands place next.",
          reviewFocusBm: "Bandingkan tempat puluh ribu seterusnya.",
        },
      },
    },
  ),
];

const difficulties = ["Easy", "Moderate", "Hard"];
const questionBanks = Object.fromEntries(
  difficulties.map((difficulty) => {
    const bankId = bankIdFor(difficulty);
    return [
      bankId,
      {
        bankId,
        topicId,
        subtopicId,
        skillId,
        yearLevel: 5,
        difficultyLevel: difficulty,
        questionIds: questions
          .filter((item) => item.bankId === bankId)
          .map((item) => item.id),
        version: CONTENT_VERSION,
        isActive: true,
        sourceMaterialId: enMaterialId,
        sourceMaterialIdBm: bmMaterialId,
      },
    ];
  }),
);

function validateQuestionBankSeed() {
  if (Object.keys(questionBanks).length !== 3) {
    throw new Error("Expected exactly three Year 5 read/write banks.");
  }
  const ids = new Set();
  for (const [bankId, bank] of Object.entries(questionBanks)) {
    if (bank.questionIds.length !== 5) {
      throw new Error(`Invalid bank ${bankId}: expected exactly five questions.`);
    }
    for (const id of bank.questionIds) {
      if (ids.has(id)) throw new Error(`Question ${id} appears more than once.`);
      ids.add(id);
    }
  }
}

module.exports = { questionBanks, questions, validateQuestionBankSeed };
