// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpBmygVdwUZNNkYc1alzrOc-MnLfEaD5s',
    appId: '1:559775119210:web:b02b25972c811124f41713',
    messagingSenderId: '559775119210',
    projectId: 'logic-oasis-fyp',
    authDomain: 'logic-oasis-fyp.firebaseapp.com',
    storageBucket: 'logic-oasis-fyp.firebasestorage.app',
    measurementId: 'G-CPEFS5XFK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpZi_BU-1A9q5gYhaLLAeoF-wjGYJUoo',
    appId: '1:559775119210:android:e2b03de7554ce31af41713',
    messagingSenderId: '559775119210',
    projectId: 'logic-oasis-fyp',
    storageBucket: 'logic-oasis-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHDpHS9ahrFFIWENTj-KCTc4spJuu6d3E',
    appId: '1:559775119210:ios:51edeb9eb4640c6ef41713',
    messagingSenderId: '559775119210',
    projectId: 'logic-oasis-fyp',
    storageBucket: 'logic-oasis-fyp.firebasestorage.app',
    iosBundleId: 'com.example.logicOasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHDpHS9ahrFFIWENTj-KCTc4spJuu6d3E',
    appId: '1:559775119210:ios:51edeb9eb4640c6ef41713',
    messagingSenderId: '559775119210',
    projectId: 'logic-oasis-fyp',
    storageBucket: 'logic-oasis-fyp.firebasestorage.app',
    iosBundleId: 'com.example.logicOasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpBmygVdwUZNNkYc1alzrOc-MnLfEaD5s',
    appId: '1:559775119210:web:c47ce61e0b2649b4f41713',
    messagingSenderId: '559775119210',
    projectId: 'logic-oasis-fyp',
    authDomain: 'logic-oasis-fyp.firebaseapp.com',
    storageBucket: 'logic-oasis-fyp.firebasestorage.app',
    measurementId: 'G-1989Y7WRQL',
  );
}
